// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.rmath

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicBoolean

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.ffi_rmath_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.ffi_rmath_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(e.toString())
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(e.toString())
        }
    }
}
// Initial value and increment amount for handles. 
// These ensure that Kotlin-generated handles always have the lowest bit set
private const val UNIFFI_HANDLEMAP_INITIAL = 1.toLong()
private const val UNIFFI_HANDLEMAP_DELTA = 2.toLong()

// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    // Start 
    private val counter = java.util.concurrent.atomic.AtomicLong(UNIFFI_HANDLEMAP_INITIAL)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(UNIFFI_HANDLEMAP_DELTA)
        map.put(handle, obj)
        return handle
    }

    // Clone a handle, creating a new one
    fun clone(handle: Long): Long {
        val obj = map.get(handle) ?: throw InternalException("UniffiHandleMap.clone: Invalid handle")
        return insert(obj)
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "rmath"
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureDroppedCallback : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceClone : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
    : Long
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFutureDroppedCallbackStruct(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureDroppedCallback? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureDroppedCallback? = null,
    ): UniffiForeignFutureDroppedCallbackStruct(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureDroppedCallbackStruct) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureResultVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultVoid.UniffiByValue,)
}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is
// rather `InterfaceTooLargeException`, caused by too many methods
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib (this)
// * IntegrityCheckingUniffiLib
// And all checksum methods are put into `IntegrityCheckingUniffiLib`
// we allow for ~2x as many methods in the UniffiLib interface.
//
// Note: above all written when we used JNA's `loadIndirect` etc.
// We now use JNA's "direct mapping" - unclear if same considerations apply exactly.
internal object IntegrityCheckingUniffiLib {
    init {
        Native.register(IntegrityCheckingUniffiLib::class.java, findLibraryName(componentName = "rmath"))
        uniffiCheckContractApiVersion(this)
        uniffiCheckApiChecksums(this)
    }
    external fun uniffi_rmath_checksum_method_rsession_bessel(
    ): Short
    external fun uniffi_rmath_checksum_method_rsession_capture_output(
    ): Short
    external fun uniffi_rmath_checksum_method_rsession_create_data_frame(
    ): Short
    external fun uniffi_rmath_checksum_method_rsession_create_matrix(
    ): Short
    external fun uniffi_rmath_checksum_method_rsession_dnorm(
    ): Short
    external fun uniffi_rmath_checksum_method_rsession_eval(
    ): Short
    external fun uniffi_rmath_checksum_method_rsession_eval_int_vector(
    ): Short
    external fun uniffi_rmath_checksum_method_rsession_eval_integer(
    ): Short
    external fun uniffi_rmath_checksum_method_rsession_eval_real(
    ): Short
    external fun uniffi_rmath_checksum_method_rsession_eval_real_vector(
    ): Short
    external fun uniffi_rmath_checksum_method_rsession_get_colnames(
    ): Short
    external fun uniffi_rmath_checksum_method_rsession_get_ncol(
    ): Short
    external fun uniffi_rmath_checksum_method_rsession_get_nrow(
    ): Short
    external fun uniffi_rmath_checksum_method_rsession_get_rownames(
    ): Short
    external fun uniffi_rmath_checksum_method_rsession_get_variable(
    ): Short
    external fun uniffi_rmath_checksum_method_rsession_is_data_frame(
    ): Short
    external fun uniffi_rmath_checksum_method_rsession_list_variables(
    ): Short
    external fun uniffi_rmath_checksum_method_rsession_math_unary(
    ): Short
    external fun uniffi_rmath_checksum_method_rsession_norm_rand(
    ): Short
    external fun uniffi_rmath_checksum_method_rsession_plot_bar(
    ): Short
    external fun uniffi_rmath_checksum_method_rsession_plot_histogram(
    ): Short
    external fun uniffi_rmath_checksum_method_rsession_plot_line(
    ): Short
    external fun uniffi_rmath_checksum_method_rsession_plot_scatter(
    ): Short
    external fun uniffi_rmath_checksum_method_rsession_pnorm(
    ): Short
    external fun uniffi_rmath_checksum_method_rsession_qnorm(
    ): Short
    external fun uniffi_rmath_checksum_method_rsession_remove_variable(
    ): Short
    external fun uniffi_rmath_checksum_method_rsession_unif_rand(
    ): Short
    external fun uniffi_rmath_checksum_constructor_rsession_new(
    ): Short
    external fun ffi_rmath_uniffi_contract_version(
    ): Int
    
        
}

internal object UniffiLib {
    
    // The Cleaner for the whole library
    internal val CLEANER: UniffiCleaner by lazy {
        UniffiCleaner.create()
    }
    

    init {
        Native.register(UniffiLib::class.java, findLibraryName(componentName = "rmath"))
        
    }
    external fun uniffi_rmath_fn_clone_rsession(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun uniffi_rmath_fn_free_rsession(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_rmath_fn_constructor_rsession_new(uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun uniffi_rmath_fn_method_rsession_bessel(`ptr`: Long,`func`: RustBuffer.ByValue,`x`: Double,`alpha`: Double,`scaled`: Byte,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    external fun uniffi_rmath_fn_method_rsession_capture_output(`ptr`: Long,`code`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_rmath_fn_method_rsession_create_data_frame(`ptr`: Long,`name`: RustBuffer.ByValue,`columns`: RustBuffer.ByValue,`names`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun uniffi_rmath_fn_method_rsession_create_matrix(`ptr`: Long,`name`: RustBuffer.ByValue,`data`: RustBuffer.ByValue,`nrow`: Int,`ncol`: Int,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun uniffi_rmath_fn_method_rsession_dnorm(`ptr`: Long,`x`: Double,`mean`: Double,`sd`: Double,`log`: Byte,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    external fun uniffi_rmath_fn_method_rsession_eval(`ptr`: Long,`code`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_rmath_fn_method_rsession_eval_int_vector(`ptr`: Long,`values`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_rmath_fn_method_rsession_eval_integer(`ptr`: Long,`value`: Int,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_rmath_fn_method_rsession_eval_real(`ptr`: Long,`value`: Double,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_rmath_fn_method_rsession_eval_real_vector(`ptr`: Long,`values`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_rmath_fn_method_rsession_get_colnames(`ptr`: Long,`name`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_rmath_fn_method_rsession_get_ncol(`ptr`: Long,`name`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun uniffi_rmath_fn_method_rsession_get_nrow(`ptr`: Long,`name`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun uniffi_rmath_fn_method_rsession_get_rownames(`ptr`: Long,`name`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_rmath_fn_method_rsession_get_variable(`ptr`: Long,`name`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_rmath_fn_method_rsession_is_data_frame(`ptr`: Long,`name`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun uniffi_rmath_fn_method_rsession_list_variables(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_rmath_fn_method_rsession_math_unary(`ptr`: Long,`func`: RustBuffer.ByValue,`x`: Double,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    external fun uniffi_rmath_fn_method_rsession_norm_rand(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    external fun uniffi_rmath_fn_method_rsession_plot_bar(`ptr`: Long,`values`: RustBuffer.ByValue,`width`: Int,`height`: Int,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_rmath_fn_method_rsession_plot_histogram(`ptr`: Long,`data`: RustBuffer.ByValue,`breaks`: Int,`width`: Int,`height`: Int,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_rmath_fn_method_rsession_plot_line(`ptr`: Long,`x`: RustBuffer.ByValue,`y`: RustBuffer.ByValue,`width`: Int,`height`: Int,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_rmath_fn_method_rsession_plot_scatter(`ptr`: Long,`x`: RustBuffer.ByValue,`y`: RustBuffer.ByValue,`width`: Int,`height`: Int,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_rmath_fn_method_rsession_pnorm(`ptr`: Long,`x`: Double,`mean`: Double,`sd`: Double,`lowerTail`: Byte,`log`: Byte,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    external fun uniffi_rmath_fn_method_rsession_qnorm(`ptr`: Long,`p`: Double,`mean`: Double,`sd`: Double,`lowerTail`: Byte,`log`: Byte,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    external fun uniffi_rmath_fn_method_rsession_remove_variable(`ptr`: Long,`name`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun uniffi_rmath_fn_method_rsession_unif_rand(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    external fun ffi_rmath_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_rmath_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_rmath_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun ffi_rmath_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_rmath_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_free_u8(`handle`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun ffi_rmath_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_free_i8(`handle`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun ffi_rmath_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_free_u16(`handle`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    external fun ffi_rmath_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_free_i16(`handle`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    external fun ffi_rmath_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_free_u32(`handle`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_rmath_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_free_i32(`handle`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_rmath_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_free_u64(`handle`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_rmath_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_free_i64(`handle`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_rmath_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_free_f32(`handle`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    external fun ffi_rmath_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_free_f64(`handle`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    external fun ffi_rmath_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_rmath_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_cancel_void(`handle`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_free_void(`handle`: Long,
    ): Unit
    external fun ffi_rmath_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    
        
}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_rmath_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
    if (lib.uniffi_rmath_checksum_method_rsession_bessel() != 20862.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rmath_checksum_method_rsession_capture_output() != 31389.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rmath_checksum_method_rsession_create_data_frame() != 54817.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rmath_checksum_method_rsession_create_matrix() != 56244.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rmath_checksum_method_rsession_dnorm() != 32507.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rmath_checksum_method_rsession_eval() != 12882.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rmath_checksum_method_rsession_eval_int_vector() != 26644.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rmath_checksum_method_rsession_eval_integer() != 44773.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rmath_checksum_method_rsession_eval_real() != 28103.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rmath_checksum_method_rsession_eval_real_vector() != 3999.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rmath_checksum_method_rsession_get_colnames() != 63026.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rmath_checksum_method_rsession_get_ncol() != 27756.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rmath_checksum_method_rsession_get_nrow() != 57474.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rmath_checksum_method_rsession_get_rownames() != 44620.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rmath_checksum_method_rsession_get_variable() != 49101.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rmath_checksum_method_rsession_is_data_frame() != 62295.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rmath_checksum_method_rsession_list_variables() != 17166.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rmath_checksum_method_rsession_math_unary() != 5708.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rmath_checksum_method_rsession_norm_rand() != 56613.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rmath_checksum_method_rsession_plot_bar() != 49543.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rmath_checksum_method_rsession_plot_histogram() != 2873.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rmath_checksum_method_rsession_plot_line() != 56958.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rmath_checksum_method_rsession_plot_scatter() != 60025.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rmath_checksum_method_rsession_pnorm() != 678.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rmath_checksum_method_rsession_qnorm() != 23170.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rmath_checksum_method_rsession_remove_variable() != 11165.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rmath_checksum_method_rsession_unif_rand() != 37007.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_rmath_checksum_constructor_rsession_new() != 1096.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
    IntegrityCheckingUniffiLib
    // UniffiLib() initialized as objects are used, but we still need to explicitly
    // reference it so initialization across crates works as expected.
    UniffiLib
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            for (arg in args) {
                when (arg) {
                    is Disposable -> arg.destroy()
                    is ArrayList<*> -> {
                        for (idx in arg.indices) {
                            val element = arg[idx]
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Map<*, *> -> {
                        for (element in arg.values) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Iterable<*> -> {
                        for (element in arg) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                }
            }
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Placeholder object used to signal that we're constructing an interface with a FFI handle.
 *
 * This is the first argument for interface constructors that input a raw handle. It exists is that
 * so we can avoid signature conflicts when an interface has a regular constructor than inputs a
 * Long.
 *
 * @suppress
 * */
object UniffiWithHandle

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoHandle
/**
 * The cleaner interface for Object finalization code to run.
 * This is the entry point to any implementation that we're using.
 *
 * The cleaner registers objects and returns cleanables, so now we are
 * defining a `UniffiCleaner` with a `UniffiClenaer.Cleanable` to abstract the
 * different implmentations available at compile time.
 *
 * @suppress
 */
interface UniffiCleaner {
    interface Cleanable {
        fun clean()
    }

    fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable

    companion object
}

// The fallback Jna cleaner, which is available for both Android, and the JVM.
private class UniffiJnaCleaner : UniffiCleaner {
    private val cleaner = com.sun.jna.internal.Cleaner.getCleaner()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        UniffiJnaCleanable(cleaner.register(value, cleanUpTask))
}

private class UniffiJnaCleanable(
    private val cleanable: com.sun.jna.internal.Cleaner.Cleanable,
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}


// We decide at uniffi binding generation time whether we were
// using Android or not.
// There are further runtime checks to chose the correct implementation
// of the cleaner.
private fun UniffiCleaner.Companion.create(): UniffiCleaner =
    try {
        // For safety's sake: if the library hasn't been run in android_cleaner = true
        // mode, but is being run on Android, then we still need to think about
        // Android API versions.
        // So we check if java.lang.ref.Cleaner is there, and use that…
        java.lang.Class.forName("java.lang.ref.Cleaner")
        JavaLangRefCleaner()
    } catch (e: ClassNotFoundException) {
        // … otherwise, fallback to the JNA cleaner.
        UniffiJnaCleaner()
    }

private class JavaLangRefCleaner : UniffiCleaner {
    val cleaner = java.lang.ref.Cleaner.create()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        JavaLangRefCleanable(cleaner.register(value, cleanUpTask))
}

private class JavaLangRefCleanable(
    val cleanable: java.lang.ref.Cleaner.Cleanable
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterInt: FfiConverter<Int, Int> {
    override fun lift(value: Int): Int {
        return value
    }

    override fun read(buf: ByteBuffer): Int {
        return buf.getInt()
    }

    override fun lower(value: Int): Int {
        return value
    }

    override fun allocationSize(value: Int) = 4UL

    override fun write(value: Int, buf: ByteBuffer) {
        buf.putInt(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterDouble: FfiConverter<Double, Double> {
    override fun lift(value: Double): Double {
        return value
    }

    override fun read(buf: ByteBuffer): Double {
        return buf.getDouble()
    }

    override fun lower(value: Double): Double {
        return value
    }

    override fun allocationSize(value: Double) = 8UL

    override fun write(value: Double, buf: ByteBuffer) {
        buf.putDouble(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}

/**
 * @suppress
 */
public object FfiConverterByteArray: FfiConverterRustBuffer<ByteArray> {
    override fun read(buf: ByteBuffer): ByteArray {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr
    }
    override fun allocationSize(value: ByteArray): ULong {
        return 4UL + value.size.toULong()
    }
    override fun write(value: ByteArray, buf: ByteBuffer) {
        buf.putInt(value.size)
        buf.put(value)
    }
}


// This template implements a class for working with a Rust struct via a handle
// to the live Rust struct on the other side of the FFI.
//
// There's some subtlety here, because we have to be careful not to operate on a Rust
// struct after it has been dropped, and because we must expose a public API for freeing
// theq Kotlin wrapper object in lieu of reliable finalizers. The core requirements are:
//
//   * Each instance holds an opaque handle to the underlying Rust struct.
//     Method calls need to read this handle from the object's state and pass it in to
//     the Rust FFI.
//
//   * When an instance is no longer needed, its handle should be passed to a
//     special destructor function provided by the Rust FFI, which will drop the
//     underlying Rust struct.
//
//   * Given an instance, calling code is expected to call the special
//     `destroy` method in order to free it after use, either by calling it explicitly
//     or by using a higher-level helper like the `use` method. Failing to do so risks
//     leaking the underlying Rust struct.
//
//   * We can't assume that calling code will do the right thing, and must be prepared
//     to handle Kotlin method calls executing concurrently with or even after a call to
//     `destroy`, and to handle multiple (possibly concurrent!) calls to `destroy`.
//
//   * We must never allow Rust code to operate on the underlying Rust struct after
//     the destructor has been called, and must never call the destructor more than once.
//     Doing so may trigger memory unsafety.
//
//   * To mitigate many of the risks of leaking memory and use-after-free unsafety, a `Cleaner`
//     is implemented to call the destructor when the Kotlin object becomes unreachable.
//     This is done in a background thread. This is not a panacea, and client code should be aware that
//      1. the thread may starve if some there are objects that have poorly performing
//     `drop` methods or do significant work in their `drop` methods.
//      2. the thread is shared across the whole library. This can be tuned by using `android_cleaner = true`,
//         or `android = true` in the [`kotlin` section of the `uniffi.toml` file](https://mozilla.github.io/uniffi-rs/kotlin/configuration.html).
//
// If we try to implement this with mutual exclusion on access to the handle, there is the
// possibility of a race between a method call and a concurrent call to `destroy`:
//
//    * Thread A starts a method call, reads the value of the handle, but is interrupted
//      before it can pass the handle over the FFI to Rust.
//    * Thread B calls `destroy` and frees the underlying Rust struct.
//    * Thread A resumes, passing the already-read handle value to Rust and triggering
//      a use-after-free.
//
// One possible solution would be to use a `ReadWriteLock`, with each method call taking
// a read lock (and thus allowed to run concurrently) and the special `destroy` method
// taking a write lock (and thus blocking on live method calls). However, we aim not to
// generate methods with any hidden blocking semantics, and a `destroy` method that might
// block if called incorrectly seems to meet that bar.
//
// So, we achieve our goals by giving each instance an associated `AtomicLong` counter to track
// the number of in-flight method calls, and an `AtomicBoolean` flag to indicate whether `destroy`
// has been called. These are updated according to the following rules:
//
//    * The initial value of the counter is 1, indicating a live object with no in-flight calls.
//      The initial value for the flag is false.
//
//    * At the start of each method call, we atomically check the counter.
//      If it is 0 then the underlying Rust struct has already been destroyed and the call is aborted.
//      If it is nonzero them we atomically increment it by 1 and proceed with the method call.
//
//    * At the end of each method call, we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
//    * When `destroy` is called, we atomically flip the flag from false to true.
//      If the flag was already true we silently fail.
//      Otherwise we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
// Astute readers may observe that this all sounds very similar to the way that Rust's `Arc<T>` works,
// and indeed it is, with the addition of a flag to guard against multiple calls to `destroy`.
//
// The overall effect is that the underlying Rust struct is destroyed only when `destroy` has been
// called *and* all in-flight method calls have completed, avoiding violating any of the expectations
// of the underlying Rust code.
//
// This makes a cleaner a better alternative to _not_ calling `destroy()` as
// and when the object is finished with, but the abstraction is not perfect: if the Rust object's `drop`
// method is slow, and/or there are many objects to cleanup, and it's on a low end Android device, then the cleaner
// thread may be starved, and the app will leak memory.
//
// In this case, `destroy`ing manually may be a better solution.
//
// The cleaner can live side by side with the manual calling of `destroy`. In the order of responsiveness, uniffi objects
// with Rust peers are reclaimed:
//
// 1. By calling the `destroy` method of the object, which calls `rustObject.free()`. If that doesn't happen:
// 2. When the object becomes unreachable, AND the Cleaner thread gets to call `rustObject.free()`. If the thread is starved then:
// 3. The memory is reclaimed when the process terminates.
//
// [1] https://stackoverflow.com/questions/24376768/can-java-finalize-an-object-when-it-is-still-in-scope/24380219
//


//
/**
 * An isolated R interpreter session.
 *
 * Each session has its own memory arena and evaluation environment.
 * This is the primary entry point for Android embedding.
 *
 * # Thread Safety
 *
 * `RSession` is `Send` but not `Sync`. Each thread should create its
 * own session. Internally, the arena uses `RefCell` which is not `Sync`.
 */
public interface RSessionInterface {
    
    /**
     * Compute a Bessel function.
     */
    fun `bessel`(`func`: RBesselFunc, `x`: kotlin.Double, `alpha`: kotlin.Double, `scaled`: kotlin.Boolean): kotlin.Double
    
    /**
     * Evaluate R code and return its formatted output.
     */
    fun `captureOutput`(`code`: kotlin.String): kotlin.String
    
    /**
     * Create a data frame variable in the global environment.
     */
    fun `createDataFrame`(`name`: kotlin.String, `columns`: List<List<kotlin.Double>>, `names`: List<kotlin.String>): kotlin.Boolean
    
    /**
     * Create a matrix variable in the global environment.
     */
    fun `createMatrix`(`name`: kotlin.String, `data`: List<kotlin.Double>, `nrow`: kotlin.Int, `ncol`: kotlin.Int): kotlin.Boolean
    
    /**
     * Probability density function for the normal distribution.
     */
    fun `dnorm`(`x`: kotlin.Double, `mean`: kotlin.Double, `sd`: kotlin.Double, `log`: kotlin.Boolean): kotlin.Double
    
    /**
     * Parse and evaluate an R expression.
     *
     * Initializes the R environment on first call, then parses the code
     * and evaluates it against the global environment.
     */
    fun `eval`(`code`: kotlin.String): RResult
    
    fun `evalIntVector`(`values`: List<kotlin.Int>): RResult
    
    fun `evalInteger`(`value`: kotlin.Int): RResult
    
    fun `evalReal`(`value`: kotlin.Double): RResult
    
    fun `evalRealVector`(`values`: List<kotlin.Double>): RResult
    
    /**
     * Get column names of a matrix or data frame.
     */
    fun `getColnames`(`name`: kotlin.String): List<kotlin.String>
    
    /**
     * Get the number of columns of a matrix or data frame.
     */
    fun `getNcol`(`name`: kotlin.String): kotlin.Int
    
    /**
     * Get the number of rows of a matrix or data frame.
     */
    fun `getNrow`(`name`: kotlin.String): kotlin.Int
    
    /**
     * Get row names of a matrix or data frame.
     */
    fun `getRownames`(`name`: kotlin.String): List<kotlin.String>
    
    /**
     * Get the formatted string representation of a variable.
     *
     * Returns `"<not found>"` if the variable does not exist.
     */
    fun `getVariable`(`name`: kotlin.String): kotlin.String
    
    /**
     * Check if a variable is a data frame.
     */
    fun `isDataFrame`(`name`: kotlin.String): kotlin.Boolean
    
    /**
     * List all variables in the global environment.
     *
     * Returns a vector of [`VariableInfo`] with name, type, and a short
     * value preview for each binding.
     */
    fun `listVariables`(): List<VariableInfo>
    
    /**
     * Compute a mathematical function on a single value.
     */
    fun `mathUnary`(`func`: RMathFunc, `x`: kotlin.Double): kotlin.Double
    
    fun `normRand`(): kotlin.Double
    
    /**
     * Render a bar chart and return the bitmap.
     */
    fun `plotBar`(`values`: List<kotlin.Double>, `width`: kotlin.UInt, `height`: kotlin.UInt): PlotImage
    
    /**
     * Render a histogram and return the bitmap.
     */
    fun `plotHistogram`(`data`: List<kotlin.Double>, `breaks`: kotlin.UInt, `width`: kotlin.UInt, `height`: kotlin.UInt): PlotImage
    
    /**
     * Render a line plot and return the bitmap.
     */
    fun `plotLine`(`x`: List<kotlin.Double>, `y`: List<kotlin.Double>, `width`: kotlin.UInt, `height`: kotlin.UInt): PlotImage
    
    /**
     * Render a scatter plot and return the bitmap.
     */
    fun `plotScatter`(`x`: List<kotlin.Double>, `y`: List<kotlin.Double>, `width`: kotlin.UInt, `height`: kotlin.UInt): PlotImage
    
    fun `pnorm`(`x`: kotlin.Double, `mean`: kotlin.Double, `sd`: kotlin.Double, `lowerTail`: kotlin.Boolean, `log`: kotlin.Boolean): kotlin.Double
    
    fun `qnorm`(`p`: kotlin.Double, `mean`: kotlin.Double, `sd`: kotlin.Double, `lowerTail`: kotlin.Boolean, `log`: kotlin.Boolean): kotlin.Double
    
    /**
     * Remove a variable from the global environment.
     *
     * Returns `true` if the variable was found and removed.
     */
    fun `removeVariable`(`name`: kotlin.String): kotlin.Boolean
    
    fun `unifRand`(): kotlin.Double
    
    companion object
}

/**
 * An isolated R interpreter session.
 *
 * Each session has its own memory arena and evaluation environment.
 * This is the primary entry point for Android embedding.
 *
 * # Thread Safety
 *
 * `RSession` is `Send` but not `Sync`. Each thread should create its
 * own session. Internally, the arena uses `RefCell` which is not `Sync`.
 */
open class RSession: Disposable, AutoCloseable, RSessionInterface
{

    @Suppress("UNUSED_PARAMETER")
    /**
     * @suppress
     */
    constructor(withHandle: UniffiWithHandle, handle: Long) {
        this.handle = handle
        this.cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(handle))
    }

    /**
     * @suppress
     *
     * This constructor can be used to instantiate a fake object. Only used for tests. Any
     * attempt to actually use an object constructed this way will fail as there is no
     * connected Rust object.
     */
    @Suppress("UNUSED_PARAMETER")
    constructor(noHandle: NoHandle) {
        this.handle = 0
        this.cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(handle))
    }
    constructor() :
        this(UniffiWithHandle, 
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_rmath_fn_constructor_rsession_new(
    
        _status)
}
    )

    protected val handle: Long
    protected val cleanable: UniffiCleaner.Cleanable

    private val wasDestroyed = AtomicBoolean(false)
    private val callCounter = AtomicLong(1)

    override fun destroy() {
        // Only allow a single call to this method.
        // TODO: maybe we should log a warning if called more than once?
        if (this.wasDestroyed.compareAndSet(false, true)) {
            // This decrement always matches the initial count of 1 given at creation time.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable.clean()
            }
        }
    }

    @Synchronized
    override fun close() {
        this.destroy()
    }

    internal inline fun <R> callWithHandle(block: (handle: Long) -> R): R {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        do {
            val c = this.callCounter.get()
            if (c == 0L) {
                throw IllegalStateException("${this.javaClass.simpleName} object has already been destroyed")
            }
            if (c == Long.MAX_VALUE) {
                throw IllegalStateException("${this.javaClass.simpleName} call counter would overflow")
            }
        } while (! this.callCounter.compareAndSet(c, c + 1L))
        // Now we can safely do the method call without the handle being freed concurrently.
        try {
            return block(this.uniffiCloneHandle())
        } finally {
            // This decrement always matches the increment we performed above.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable.clean()
            }
        }
    }

    // Use a static inner class instead of a closure so as not to accidentally
    // capture `this` as part of the cleanable's action.
    private class UniffiCleanAction(private val handle: Long) : Runnable {
        override fun run() {
            if (handle == 0.toLong()) {
                // Fake object created with `NoHandle`, don't try to free.
                return;
            }
            uniffiRustCall { status ->
                UniffiLib.uniffi_rmath_fn_free_rsession(handle, status)
            }
        }
    }

    /**
     * @suppress
     */
    fun uniffiCloneHandle(): Long {
        if (handle == 0.toLong()) {
            throw InternalException("uniffiCloneHandle() called on NoHandle object");
        }
        return uniffiRustCall() { status ->
            UniffiLib.uniffi_rmath_fn_clone_rsession(handle, status)
        }
    }

    
    /**
     * Compute a Bessel function.
     */override fun `bessel`(`func`: RBesselFunc, `x`: kotlin.Double, `alpha`: kotlin.Double, `scaled`: kotlin.Boolean): kotlin.Double {
            return FfiConverterDouble.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_rmath_fn_method_rsession_bessel(
        it,
        FfiConverterTypeRBesselFunc.lower(`func`),FfiConverterDouble.lower(`x`),FfiConverterDouble.lower(`alpha`),FfiConverterBoolean.lower(`scaled`),_status)
}
    }
    )
    }
    

    
    /**
     * Evaluate R code and return its formatted output.
     */override fun `captureOutput`(`code`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_rmath_fn_method_rsession_capture_output(
        it,
        FfiConverterString.lower(`code`),_status)
}
    }
    )
    }
    

    
    /**
     * Create a data frame variable in the global environment.
     */override fun `createDataFrame`(`name`: kotlin.String, `columns`: List<List<kotlin.Double>>, `names`: List<kotlin.String>): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_rmath_fn_method_rsession_create_data_frame(
        it,
        FfiConverterString.lower(`name`),FfiConverterSequenceSequenceDouble.lower(`columns`),FfiConverterSequenceString.lower(`names`),_status)
}
    }
    )
    }
    

    
    /**
     * Create a matrix variable in the global environment.
     */override fun `createMatrix`(`name`: kotlin.String, `data`: List<kotlin.Double>, `nrow`: kotlin.Int, `ncol`: kotlin.Int): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_rmath_fn_method_rsession_create_matrix(
        it,
        FfiConverterString.lower(`name`),FfiConverterSequenceDouble.lower(`data`),FfiConverterInt.lower(`nrow`),FfiConverterInt.lower(`ncol`),_status)
}
    }
    )
    }
    

    
    /**
     * Probability density function for the normal distribution.
     */override fun `dnorm`(`x`: kotlin.Double, `mean`: kotlin.Double, `sd`: kotlin.Double, `log`: kotlin.Boolean): kotlin.Double {
            return FfiConverterDouble.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_rmath_fn_method_rsession_dnorm(
        it,
        FfiConverterDouble.lower(`x`),FfiConverterDouble.lower(`mean`),FfiConverterDouble.lower(`sd`),FfiConverterBoolean.lower(`log`),_status)
}
    }
    )
    }
    

    
    /**
     * Parse and evaluate an R expression.
     *
     * Initializes the R environment on first call, then parses the code
     * and evaluates it against the global environment.
     */override fun `eval`(`code`: kotlin.String): RResult {
            return FfiConverterTypeRResult.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_rmath_fn_method_rsession_eval(
        it,
        FfiConverterString.lower(`code`),_status)
}
    }
    )
    }
    

    override fun `evalIntVector`(`values`: List<kotlin.Int>): RResult {
            return FfiConverterTypeRResult.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_rmath_fn_method_rsession_eval_int_vector(
        it,
        FfiConverterSequenceInt.lower(`values`),_status)
}
    }
    )
    }
    

    override fun `evalInteger`(`value`: kotlin.Int): RResult {
            return FfiConverterTypeRResult.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_rmath_fn_method_rsession_eval_integer(
        it,
        FfiConverterInt.lower(`value`),_status)
}
    }
    )
    }
    

    override fun `evalReal`(`value`: kotlin.Double): RResult {
            return FfiConverterTypeRResult.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_rmath_fn_method_rsession_eval_real(
        it,
        FfiConverterDouble.lower(`value`),_status)
}
    }
    )
    }
    

    override fun `evalRealVector`(`values`: List<kotlin.Double>): RResult {
            return FfiConverterTypeRResult.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_rmath_fn_method_rsession_eval_real_vector(
        it,
        FfiConverterSequenceDouble.lower(`values`),_status)
}
    }
    )
    }
    

    
    /**
     * Get column names of a matrix or data frame.
     */override fun `getColnames`(`name`: kotlin.String): List<kotlin.String> {
            return FfiConverterSequenceString.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_rmath_fn_method_rsession_get_colnames(
        it,
        FfiConverterString.lower(`name`),_status)
}
    }
    )
    }
    

    
    /**
     * Get the number of columns of a matrix or data frame.
     */override fun `getNcol`(`name`: kotlin.String): kotlin.Int {
            return FfiConverterInt.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_rmath_fn_method_rsession_get_ncol(
        it,
        FfiConverterString.lower(`name`),_status)
}
    }
    )
    }
    

    
    /**
     * Get the number of rows of a matrix or data frame.
     */override fun `getNrow`(`name`: kotlin.String): kotlin.Int {
            return FfiConverterInt.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_rmath_fn_method_rsession_get_nrow(
        it,
        FfiConverterString.lower(`name`),_status)
}
    }
    )
    }
    

    
    /**
     * Get row names of a matrix or data frame.
     */override fun `getRownames`(`name`: kotlin.String): List<kotlin.String> {
            return FfiConverterSequenceString.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_rmath_fn_method_rsession_get_rownames(
        it,
        FfiConverterString.lower(`name`),_status)
}
    }
    )
    }
    

    
    /**
     * Get the formatted string representation of a variable.
     *
     * Returns `"<not found>"` if the variable does not exist.
     */override fun `getVariable`(`name`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_rmath_fn_method_rsession_get_variable(
        it,
        FfiConverterString.lower(`name`),_status)
}
    }
    )
    }
    

    
    /**
     * Check if a variable is a data frame.
     */override fun `isDataFrame`(`name`: kotlin.String): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_rmath_fn_method_rsession_is_data_frame(
        it,
        FfiConverterString.lower(`name`),_status)
}
    }
    )
    }
    

    
    /**
     * List all variables in the global environment.
     *
     * Returns a vector of [`VariableInfo`] with name, type, and a short
     * value preview for each binding.
     */override fun `listVariables`(): List<VariableInfo> {
            return FfiConverterSequenceTypeVariableInfo.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_rmath_fn_method_rsession_list_variables(
        it,
        _status)
}
    }
    )
    }
    

    
    /**
     * Compute a mathematical function on a single value.
     */override fun `mathUnary`(`func`: RMathFunc, `x`: kotlin.Double): kotlin.Double {
            return FfiConverterDouble.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_rmath_fn_method_rsession_math_unary(
        it,
        FfiConverterTypeRMathFunc.lower(`func`),FfiConverterDouble.lower(`x`),_status)
}
    }
    )
    }
    

    override fun `normRand`(): kotlin.Double {
            return FfiConverterDouble.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_rmath_fn_method_rsession_norm_rand(
        it,
        _status)
}
    }
    )
    }
    

    
    /**
     * Render a bar chart and return the bitmap.
     */override fun `plotBar`(`values`: List<kotlin.Double>, `width`: kotlin.UInt, `height`: kotlin.UInt): PlotImage {
            return FfiConverterTypePlotImage.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_rmath_fn_method_rsession_plot_bar(
        it,
        FfiConverterSequenceDouble.lower(`values`),FfiConverterUInt.lower(`width`),FfiConverterUInt.lower(`height`),_status)
}
    }
    )
    }
    

    
    /**
     * Render a histogram and return the bitmap.
     */override fun `plotHistogram`(`data`: List<kotlin.Double>, `breaks`: kotlin.UInt, `width`: kotlin.UInt, `height`: kotlin.UInt): PlotImage {
            return FfiConverterTypePlotImage.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_rmath_fn_method_rsession_plot_histogram(
        it,
        FfiConverterSequenceDouble.lower(`data`),FfiConverterUInt.lower(`breaks`),FfiConverterUInt.lower(`width`),FfiConverterUInt.lower(`height`),_status)
}
    }
    )
    }
    

    
    /**
     * Render a line plot and return the bitmap.
     */override fun `plotLine`(`x`: List<kotlin.Double>, `y`: List<kotlin.Double>, `width`: kotlin.UInt, `height`: kotlin.UInt): PlotImage {
            return FfiConverterTypePlotImage.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_rmath_fn_method_rsession_plot_line(
        it,
        FfiConverterSequenceDouble.lower(`x`),FfiConverterSequenceDouble.lower(`y`),FfiConverterUInt.lower(`width`),FfiConverterUInt.lower(`height`),_status)
}
    }
    )
    }
    

    
    /**
     * Render a scatter plot and return the bitmap.
     */override fun `plotScatter`(`x`: List<kotlin.Double>, `y`: List<kotlin.Double>, `width`: kotlin.UInt, `height`: kotlin.UInt): PlotImage {
            return FfiConverterTypePlotImage.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_rmath_fn_method_rsession_plot_scatter(
        it,
        FfiConverterSequenceDouble.lower(`x`),FfiConverterSequenceDouble.lower(`y`),FfiConverterUInt.lower(`width`),FfiConverterUInt.lower(`height`),_status)
}
    }
    )
    }
    

    override fun `pnorm`(`x`: kotlin.Double, `mean`: kotlin.Double, `sd`: kotlin.Double, `lowerTail`: kotlin.Boolean, `log`: kotlin.Boolean): kotlin.Double {
            return FfiConverterDouble.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_rmath_fn_method_rsession_pnorm(
        it,
        FfiConverterDouble.lower(`x`),FfiConverterDouble.lower(`mean`),FfiConverterDouble.lower(`sd`),FfiConverterBoolean.lower(`lowerTail`),FfiConverterBoolean.lower(`log`),_status)
}
    }
    )
    }
    

    override fun `qnorm`(`p`: kotlin.Double, `mean`: kotlin.Double, `sd`: kotlin.Double, `lowerTail`: kotlin.Boolean, `log`: kotlin.Boolean): kotlin.Double {
            return FfiConverterDouble.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_rmath_fn_method_rsession_qnorm(
        it,
        FfiConverterDouble.lower(`p`),FfiConverterDouble.lower(`mean`),FfiConverterDouble.lower(`sd`),FfiConverterBoolean.lower(`lowerTail`),FfiConverterBoolean.lower(`log`),_status)
}
    }
    )
    }
    

    
    /**
     * Remove a variable from the global environment.
     *
     * Returns `true` if the variable was found and removed.
     */override fun `removeVariable`(`name`: kotlin.String): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_rmath_fn_method_rsession_remove_variable(
        it,
        FfiConverterString.lower(`name`),_status)
}
    }
    )
    }
    

    override fun `unifRand`(): kotlin.Double {
            return FfiConverterDouble.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_rmath_fn_method_rsession_unif_rand(
        it,
        _status)
}
    }
    )
    }
    

    

    


    
    
    /**
     * @suppress
     */
    companion object
    
}


/**
 * @suppress
 */
public object FfiConverterTypeRSession: FfiConverter<RSession, Long> {
    override fun lower(value: RSession): Long {
        return value.uniffiCloneHandle()
    }

    override fun lift(value: Long): RSession {
        return RSession(UniffiWithHandle, value)
    }

    override fun read(buf: ByteBuffer): RSession {
        return lift(buf.getLong())
    }

    override fun allocationSize(value: RSession) = 8UL

    override fun write(value: RSession, buf: ByteBuffer) {
        buf.putLong(lower(value))
    }
}



/**
 * RGBA bitmap image returned from plot functions.
 */
data class PlotImage (
    var `width`: kotlin.UInt
    , 
    var `height`: kotlin.UInt
    , 
    var `rgbaBytes`: kotlin.ByteArray
    
){
    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypePlotImage: FfiConverterRustBuffer<PlotImage> {
    override fun read(buf: ByteBuffer): PlotImage {
        return PlotImage(
            FfiConverterUInt.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterByteArray.read(buf),
        )
    }

    override fun allocationSize(value: PlotImage) = (
            FfiConverterUInt.allocationSize(value.`width`) +
            FfiConverterUInt.allocationSize(value.`height`) +
            FfiConverterByteArray.allocationSize(value.`rgbaBytes`)
    )

    override fun write(value: PlotImage, buf: ByteBuffer) {
            FfiConverterUInt.write(value.`width`, buf)
            FfiConverterUInt.write(value.`height`, buf)
            FfiConverterByteArray.write(value.`rgbaBytes`, buf)
    }
}



/**
 * Result of an R evaluation.
 */
data class RResult (
    var `value`: kotlin.Double
    , 
    var `output`: kotlin.String
    
){
    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeRResult: FfiConverterRustBuffer<RResult> {
    override fun read(buf: ByteBuffer): RResult {
        return RResult(
            FfiConverterDouble.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: RResult) = (
            FfiConverterDouble.allocationSize(value.`value`) +
            FfiConverterString.allocationSize(value.`output`)
    )

    override fun write(value: RResult, buf: ByteBuffer) {
            FfiConverterDouble.write(value.`value`, buf)
            FfiConverterString.write(value.`output`, buf)
    }
}



/**
 * Information about a variable in the R environment.
 */
data class VariableInfo (
    var `name`: kotlin.String
    , 
    var `typeName`: kotlin.String
    , 
    var `preview`: kotlin.String
    
){
    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeVariableInfo: FfiConverterRustBuffer<VariableInfo> {
    override fun read(buf: ByteBuffer): VariableInfo {
        return VariableInfo(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: VariableInfo) = (
            FfiConverterString.allocationSize(value.`name`) +
            FfiConverterString.allocationSize(value.`typeName`) +
            FfiConverterString.allocationSize(value.`preview`)
    )

    override fun write(value: VariableInfo, buf: ByteBuffer) {
            FfiConverterString.write(value.`name`, buf)
            FfiConverterString.write(value.`typeName`, buf)
            FfiConverterString.write(value.`preview`, buf)
    }
}



/**
 * Supported Bessel function families.
 */

enum class RBesselFunc {
    
    J,
    Y,
    I,
    K;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeRBesselFunc: FfiConverterRustBuffer<RBesselFunc> {
    override fun read(buf: ByteBuffer) = try {
        RBesselFunc.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: RBesselFunc) = 4UL

    override fun write(value: RBesselFunc, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}





/**
 * Supported mathematical functions.
 */

enum class RMathFunc {
    
    ABS,
    SQRT,
    CEIL,
    FLOOR,
    TRUNC,
    EXP,
    LOG,
    LOG2,
    LOG10,
    SIN,
    COS,
    TAN,
    ASIN,
    ACOS,
    ATAN,
    GAMMA,
    LGAMMA;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeRMathFunc: FfiConverterRustBuffer<RMathFunc> {
    override fun read(buf: ByteBuffer) = try {
        RMathFunc.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: RMathFunc) = 4UL

    override fun write(value: RMathFunc, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






/**
 * @suppress
 */
public object FfiConverterSequenceInt: FfiConverterRustBuffer<List<kotlin.Int>> {
    override fun read(buf: ByteBuffer): List<kotlin.Int> {
        val len = buf.getInt()
        return List<kotlin.Int>(len) {
            FfiConverterInt.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.Int>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterInt.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.Int>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterInt.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceDouble: FfiConverterRustBuffer<List<kotlin.Double>> {
    override fun read(buf: ByteBuffer): List<kotlin.Double> {
        val len = buf.getInt()
        return List<kotlin.Double>(len) {
            FfiConverterDouble.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.Double>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterDouble.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.Double>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterDouble.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceString: FfiConverterRustBuffer<List<kotlin.String>> {
    override fun read(buf: ByteBuffer): List<kotlin.String> {
        val len = buf.getInt()
        return List<kotlin.String>(len) {
            FfiConverterString.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.String>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterString.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterString.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeVariableInfo: FfiConverterRustBuffer<List<VariableInfo>> {
    override fun read(buf: ByteBuffer): List<VariableInfo> {
        val len = buf.getInt()
        return List<VariableInfo>(len) {
            FfiConverterTypeVariableInfo.read(buf)
        }
    }

    override fun allocationSize(value: List<VariableInfo>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeVariableInfo.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<VariableInfo>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeVariableInfo.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceSequenceDouble: FfiConverterRustBuffer<List<List<kotlin.Double>>> {
    override fun read(buf: ByteBuffer): List<List<kotlin.Double>> {
        val len = buf.getInt()
        return List<List<kotlin.Double>>(len) {
            FfiConverterSequenceDouble.read(buf)
        }
    }

    override fun allocationSize(value: List<List<kotlin.Double>>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterSequenceDouble.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<List<kotlin.Double>>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterSequenceDouble.write(it, buf)
        }
    }
}

