//! Port of plural.c -- Bison-generated plural expression parser.
//!
//! This file contains the plural expression parser generated by GNU Bison.
//! In the C version, this is a 1962-line LALR(1) parser. For the standalone
//! Rust port, we provide a simplified recursive-descent parser that handles
//! the subset of plural expressions used in practice by GNU gettext .mo files.
//!
//! The plural expression grammar (simplified):
//! ```text
//!   expr     -> expr '?' expr ':' expr   (ternary, lowest precedence)
//!            | expr "||" expr
//!            | expr "&&" expr
//!            | expr "==" expr
//!            | expr "!=" expr
//!            | expr ">=" expr
//!            | expr "<=" expr
//!            | expr ">" expr
//!            | expr "<" expr
//!            | expr "+" expr
//!            | expr "-" expr
//!            | expr "*" expr
//!            | expr "/" expr
//!            | expr "%" expr
//!            | "!" expr                   (logical NOT)
//!            | "n"
//!            | number
//!            | "(" expr ")"
//! ```

#![allow(non_snake_case, dead_code)]

use std::alloc::Layout;
use std::os::raw::{c_char, c_int, c_ulong};
use std::ptr;

use super::types::*;

// ---------------------------------------------------------------------------
// Parser return codes (matching Bison yysyntax_error values)
// ---------------------------------------------------------------------------

/// Internal parser state. In the C Bison-generated parser this is a large
/// stack-based LALR(1) parser. We replace it with a simple recursive-descent
/// parser that produces the same expression tree.
pub(crate) struct PluralParser {
    /// Current position in the input string.
    cp: *const c_char,
}

impl PluralParser {
    /// Create a new parser starting at the given string position.
    pub unsafe fn new(cp: *const c_char) -> Self {
        PluralParser { cp }
    }

    /// Peek at the current character without consuming it.
    unsafe fn peek(&self) -> c_char {
        unsafe {
            if self.cp.is_null() || *self.cp == 0 {
                0
            } else {
                *self.cp
            }
        }
    }

    /// Consume and return the current character.
    unsafe fn next(&mut self) -> c_char {
        unsafe {
            let c = self.peek();
            if c != 0 {
                self.cp = self.cp.add(1);
            }
            c
        }
    }

    /// Skip whitespace.
    unsafe fn skip_whitespace(&mut self) {
        unsafe {
            while !self.cp.is_null() && *self.cp != 0 {
                let c = *self.cp as u8;
                if c == b' ' || c == b'\t' || c == b'\n' || c == b'\r' {
                    self.cp = self.cp.add(1);
                } else {
                    break;
                }
            }
        }
    }

    /// Parse a number (unsigned integer).
    unsafe fn parse_number(&mut self) -> Option<c_ulong> {
        unsafe {
            let mut n: c_ulong = 0;
            let mut found = false;
            while !self.cp.is_null() && *self.cp != 0 {
                let c = *self.cp as u8;
                if c >= b'0' && c <= b'9' {
                    n = n.wrapping_mul(10).wrapping_add((c - b'0') as c_ulong);
                    self.cp = self.cp.add(1);
                    found = true;
                } else {
                    break;
                }
            }
            if found { Some(n) } else { None }
        }
    }

    /// Allocate a new expression node.
    unsafe fn alloc_expr(nargs: c_int, op: expression_operator) -> *mut expression {
        unsafe {
            let layout = Layout::new::<expression>();
            let p = std::alloc::alloc(layout) as *mut expression;
            if p.is_null() {
                return ptr::null_mut();
            }
            (*p).nargs = nargs;
            (*p).operation = op;
            (*p).val = expression_val { num: 0 };
            p
        }
    }

    // ---- Recursive descent parser ----

    /// Parse a full plural expression.
    pub unsafe fn parse(&mut self) -> *mut expression {
        unsafe {
            self.skip_whitespace();
            let result = self.parse_ternary();
            self.skip_whitespace();
            // Expect ';' at the end (plural expressions end with semicolon).
            if self.peek() == b';' as c_char {
                self.next();
            }
            result
        }
    }

    /// Parse ternary: expr ? expr : expr (right-associative).
    unsafe fn parse_ternary(&mut self) -> *mut expression {
        unsafe {
            let cond = self.parse_or();
            self.skip_whitespace();
            if self.peek() == b'?' as c_char {
                self.next();
                self.skip_whitespace();
                let then_expr = self.parse_ternary();
                self.skip_whitespace();
                if self.peek() == b':' as c_char {
                    self.next();
                    self.skip_whitespace();
                    let else_expr = self.parse_ternary();
                    let node = Self::alloc_expr(3, expression_operator::qmop);
                    if node.is_null() {
                        return ptr::null_mut();
                    }
                    (*node).val.args = [cond, then_expr, else_expr];
                    return node;
                }
            }
            cond
        }
    }

    /// Parse logical OR.
    unsafe fn parse_or(&mut self) -> *mut expression {
        unsafe {
            let mut left = self.parse_and();
            loop {
                self.skip_whitespace();
                if self.peek() == b'|' as c_char {
                    self.next();
                    if self.peek() == b'|' as c_char {
                        self.next();
                        self.skip_whitespace();
                        let right = self.parse_and();
                        let node = Self::alloc_expr(2, expression_operator::lor);
                        if node.is_null() {
                            return ptr::null_mut();
                        }
                        (*node).val.args = [left, right, ptr::null_mut()];
                        left = node;
                    } else {
                        break;
                    }
                } else {
                    break;
                }
            }
            left
        }
    }

    /// Parse logical AND.
    unsafe fn parse_and(&mut self) -> *mut expression {
        unsafe {
            let mut left = self.parse_equality();
            loop {
                self.skip_whitespace();
                if self.peek() == b'&' as c_char {
                    self.next();
                    if self.peek() == b'&' as c_char {
                        self.next();
                        self.skip_whitespace();
                        let right = self.parse_equality();
                        let node = Self::alloc_expr(2, expression_operator::land);
                        if node.is_null() {
                            return ptr::null_mut();
                        }
                        (*node).val.args = [left, right, ptr::null_mut()];
                        left = node;
                    } else {
                        break;
                    }
                } else {
                    break;
                }
            }
            left
        }
    }

    /// Parse equality operators (== and !=).
    unsafe fn parse_equality(&mut self) -> *mut expression {
        unsafe {
            let mut left = self.parse_comparison();
            loop {
                self.skip_whitespace();
                let c = self.peek();
                if c == b'=' as c_char {
                    self.next();
                    if self.peek() == b'=' as c_char {
                        self.next();
                        self.skip_whitespace();
                        let right = self.parse_comparison();
                        let node = Self::alloc_expr(2, expression_operator::equal);
                        if node.is_null() {
                            return ptr::null_mut();
                        }
                        (*node).val.args = [left, right, ptr::null_mut()];
                        left = node;
                    } else {
                        break;
                    }
                } else if c == b'!' as c_char {
                    self.next();
                    if self.peek() == b'=' as c_char {
                        self.next();
                        self.skip_whitespace();
                        let right = self.parse_comparison();
                        let node = Self::alloc_expr(2, expression_operator::not_equal);
                        if node.is_null() {
                            return ptr::null_mut();
                        }
                        (*node).val.args = [left, right, ptr::null_mut()];
                        left = node;
                    } else {
                        break;
                    }
                } else {
                    break;
                }
            }
            left
        }
    }

    /// Parse comparison operators (>=, <=, >, <).
    unsafe fn parse_comparison(&mut self) -> *mut expression {
        unsafe {
            let left = self.parse_additive();
            self.skip_whitespace();
            let c = self.peek();
            if c == b'>' as c_char {
                self.next();
                if self.peek() == b'=' as c_char {
                    self.next();
                    self.skip_whitespace();
                    let right = self.parse_additive();
                    let node = Self::alloc_expr(2, expression_operator::greater_or_equal);
                    if node.is_null() {
                        return ptr::null_mut();
                    }
                    (*node).val.args = [left, right, ptr::null_mut()];
                    node
                } else {
                    self.skip_whitespace();
                    let right = self.parse_additive();
                    let node = Self::alloc_expr(2, expression_operator::greater_than);
                    if node.is_null() {
                        return ptr::null_mut();
                    }
                    (*node).val.args = [left, right, ptr::null_mut()];
                    node
                }
            } else if c == b'<' as c_char {
                self.next();
                if self.peek() == b'=' as c_char {
                    self.next();
                    self.skip_whitespace();
                    let right = self.parse_additive();
                    let node = Self::alloc_expr(2, expression_operator::less_or_equal);
                    if node.is_null() {
                        return ptr::null_mut();
                    }
                    (*node).val.args = [left, right, ptr::null_mut()];
                    node
                } else {
                    self.skip_whitespace();
                    let right = self.parse_additive();
                    let node = Self::alloc_expr(2, expression_operator::less_than);
                    if node.is_null() {
                        return ptr::null_mut();
                    }
                    (*node).val.args = [left, right, ptr::null_mut()];
                    node
                }
            } else {
                left
            }
        }
    }

    /// Parse additive operators (+ and -).
    unsafe fn parse_additive(&mut self) -> *mut expression {
        unsafe {
            let mut left = self.parse_multiplicative();
            loop {
                self.skip_whitespace();
                let c = self.peek();
                if c == b'+' as c_char {
                    self.next();
                    self.skip_whitespace();
                    let right = self.parse_multiplicative();
                    let node = Self::alloc_expr(2, expression_operator::plus);
                    if node.is_null() {
                        return ptr::null_mut();
                    }
                    (*node).val.args = [left, right, ptr::null_mut()];
                    left = node;
                } else if c == b'-' as c_char {
                    self.next();
                    self.skip_whitespace();
                    let right = self.parse_multiplicative();
                    let node = Self::alloc_expr(2, expression_operator::minus);
                    if node.is_null() {
                        return ptr::null_mut();
                    }
                    (*node).val.args = [left, right, ptr::null_mut()];
                    left = node;
                } else {
                    break;
                }
            }
            left
        }
    }

    /// Parse multiplicative operators (*, /, %).
    unsafe fn parse_multiplicative(&mut self) -> *mut expression {
        unsafe {
            let mut left = self.parse_unary();
            loop {
                self.skip_whitespace();
                let c = self.peek();
                if c == b'*' as c_char {
                    self.next();
                    self.skip_whitespace();
                    let right = self.parse_unary();
                    let node = Self::alloc_expr(2, expression_operator::mult);
                    if node.is_null() {
                        return ptr::null_mut();
                    }
                    (*node).val.args = [left, right, ptr::null_mut()];
                    left = node;
                } else if c == b'/' as c_char {
                    self.next();
                    self.skip_whitespace();
                    let right = self.parse_unary();
                    let node = Self::alloc_expr(2, expression_operator::divide);
                    if node.is_null() {
                        return ptr::null_mut();
                    }
                    (*node).val.args = [left, right, ptr::null_mut()];
                    left = node;
                } else if c == b'%' as c_char {
                    self.next();
                    self.skip_whitespace();
                    let right = self.parse_unary();
                    let node = Self::alloc_expr(2, expression_operator::module);
                    if node.is_null() {
                        return ptr::null_mut();
                    }
                    (*node).val.args = [left, right, ptr::null_mut()];
                    left = node;
                } else {
                    break;
                }
            }
            left
        }
    }

    /// Parse unary operators (!).
    unsafe fn parse_unary(&mut self) -> *mut expression {
        unsafe {
            self.skip_whitespace();
            if self.peek() == b'!' as c_char {
                self.next();
                self.skip_whitespace();
                let operand = self.parse_unary();
                let node = Self::alloc_expr(1, expression_operator::lnot);
                if node.is_null() {
                    return ptr::null_mut();
                }
                (*node).val.args = [operand, ptr::null_mut(), ptr::null_mut()];
                node
            } else {
                self.parse_primary()
            }
        }
    }

    /// Parse primary: 'n', number, or '(' expr ')'.
    unsafe fn parse_primary(&mut self) -> *mut expression {
        unsafe {
            self.skip_whitespace();
            let c = self.peek();

            if c == b'n' as c_char {
                self.next();
                let node = Self::alloc_expr(0, expression_operator::var);
                if !node.is_null() {
                    (*node).val = expression_val { num: 0 };
                }
                node
            } else if c == b'(' as c_char {
                self.next();
                self.skip_whitespace();
                let inner = self.parse_ternary();
                self.skip_whitespace();
                if self.peek() == b')' as c_char {
                    self.next();
                }
                inner
            } else if c >= b'0' as c_char && c <= b'9' as c_char {
                let n = self.parse_number().unwrap_or(0);
                let node = Self::alloc_expr(0, expression_operator::num);
                if !node.is_null() {
                    (*node).val = expression_val { num: n };
                }
                node
            } else {
                ptr::null_mut()
            }
        }
    }
}

// ---------------------------------------------------------------------------
// FFI: Bison parser entry point
// ---------------------------------------------------------------------------

/// Parse a plural expression from the string in `arg->cp`.
///
/// This replaces the Bison-generated `libintl_gettextparse()` function.
/// On success, sets `arg->res` to the parsed expression tree and returns 0.
/// On failure, returns -1.
///
/// # Safety
/// `arg` must be a valid pointer to a `parse_args` struct.
pub unsafe fn libintl_gettextparse(arg: *mut parse_args) -> c_int {
    unsafe {
        if arg.is_null() {
            return -1;
        }

        let cp = (*arg).cp;
        if cp.is_null() {
            return -1;
        }

        let mut parser = PluralParser::new(cp);
        let result = parser.parse();

        if result.is_null() {
            -1
        } else {
            (*arg).res = result;
            0
        }
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::super::plural_exp::plural_eval;
    use super::*;

    unsafe fn parse_plural(expr: &str) -> *mut expression {
        let mut bytes = expr.as_bytes().to_vec();
        bytes.push(0);
        let mut parser = unsafe { PluralParser::new(bytes.as_ptr() as *const c_char) };
        unsafe { parser.parse() }
    }

    unsafe fn free_expr(p: *mut expression) {
        if p.is_null() {
            return;
        }
        match unsafe { (*p).operation } {
            expression_operator::var | expression_operator::num => {}
            expression_operator::lnot => {
                unsafe { free_expr((*p).val.args[0]) };
            }
            _ => {
                if unsafe { (*p).nargs } >= 1 {
                    unsafe { free_expr((*p).val.args[0]) };
                }
                if unsafe { (*p).nargs } >= 2 {
                    unsafe { free_expr((*p).val.args[1]) };
                }
                if unsafe { (*p).nargs } >= 3 {
                    unsafe { free_expr((*p).val.args[2]) };
                }
            }
        }
        let layout = Layout::new::<expression>();
        unsafe { std::alloc::dealloc(p as *mut u8, layout) };
    }

    #[test]
    fn test_parse_n() {
        unsafe {
            let expr = parse_plural("n");
            assert!(!expr.is_null());
            assert_eq!((*expr).operation, expression_operator::var);
            free_expr(expr);
        }
    }

    #[test]
    fn test_parse_number() {
        unsafe {
            let expr = parse_plural("42");
            assert!(!expr.is_null());
            assert_eq!((*expr).operation, expression_operator::num);
            assert_eq!((*expr).val.get_num(), 42);
            free_expr(expr);
        }
    }

    #[test]
    fn test_parse_n_not_eq_1() {
        unsafe {
            let expr = parse_plural("n != 1");
            assert!(!expr.is_null());
            assert_eq!((*expr).operation, expression_operator::not_equal);
            assert_eq!(plural_eval(expr, 1), 0);
            assert_eq!(plural_eval(expr, 2), 1);
            free_expr(expr);
        }
    }

    #[test]
    fn test_parse_ternary() {
        unsafe {
            let expr = parse_plural("n == 1 ? 0 : 1");
            assert!(!expr.is_null());
            assert_eq!(plural_eval(expr, 1), 0);
            assert_eq!(plural_eval(expr, 2), 1);
            free_expr(expr);
        }
    }

    #[test]
    fn test_parse_complex() {
        unsafe {
            let expr_str =
                "n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2;";
            let expr = parse_plural(expr_str);
            assert!(!expr.is_null());
            assert_eq!(plural_eval(expr, 1), 0);
            assert_eq!(plural_eval(expr, 5), 2);
            assert_eq!(plural_eval(expr, 21), 0);
            free_expr(expr);
        }
    }

    #[test]
    fn test_parse_with_semicolon() {
        unsafe {
            let expr = parse_plural("n != 1;");
            assert!(!expr.is_null());
            assert_eq!(plural_eval(expr, 1), 0);
            free_expr(expr);
        }
    }

    #[test]
    fn test_parse_not() {
        unsafe {
            let expr = parse_plural("!n");
            assert!(!expr.is_null());
            assert_eq!((*expr).operation, expression_operator::lnot);
            assert_eq!(plural_eval(expr, 0), 1);
            assert_eq!(plural_eval(expr, 5), 0);
            free_expr(expr);
        }
    }

    #[test]
    fn test_parse_modulo() {
        unsafe {
            let expr = parse_plural("n % 3");
            assert!(!expr.is_null());
            assert_eq!(plural_eval(expr, 7), 1);
            free_expr(expr);
        }
    }
}
