#![allow(non_snake_case, non_upper_case_globals, unused_variables)]

pub mod CommandLineArgs;
pub mod Rmain;
pub mod agrep;
pub mod all_equal;
pub mod alloca;
#[cfg(feature = "altrep")]
pub mod altclasses;
#[cfg(feature = "altrep")]
pub mod altrep;
pub mod apply;
pub mod arithmetic;
pub mod array;
pub mod attrib;
pub mod bind;
pub mod browser_files;
pub mod builtin;
pub mod character;
pub mod clippath;
pub mod coerce;
pub mod colors;
pub mod complex_cmath;
pub mod connections;
pub mod cum;
pub mod datetime;
pub mod dcf;
pub mod debug;
pub mod deparse;
pub mod dotcode;
pub mod dstruct;
pub mod duplicate;
pub mod edit;
pub mod engine;
pub mod envir;
pub mod errors;
pub mod essentials;
pub mod essentials_basic;
pub mod flexiblas;
pub mod format;
pub mod gram_ex;
pub mod gram_main;
pub mod graphics_ffi;
pub mod grep;
pub mod identical;
pub mod inlined;
pub mod inspect;
pub mod lapack;
pub mod list;
pub mod localecharset;
pub mod logic;
pub mod machar;
pub mod machine;
pub mod main;
pub mod mapply;
pub mod mask;
pub mod match_mod;
pub mod memory_main;
pub mod mkdtemp;
pub mod names;
pub mod objects;
pub mod options;
pub mod paste;
pub mod paste_impl;
pub mod paths;
pub mod patterns;
pub mod platform;
pub mod polyroot;
pub mod print;
pub mod printarray;
pub mod printutils;
pub mod printvector;
pub mod qr;
pub mod qr_apply;
pub mod qr_extract;
pub mod qr_q;
pub mod qsort;
pub mod r_format;
pub mod radixsort;
pub mod random;
pub mod raw;
pub mod raw_heap;
pub mod rdynload;
pub mod registration;
pub mod relop;
pub mod rfile;
pub mod rlocale;
pub mod rng;
pub mod rng_dispatch;
pub mod rstrptime;
pub mod saveload;
pub mod scan;
pub mod seq;
pub mod serialize;
pub mod sort;
pub mod source;
pub mod split;
pub mod sprintf_main;
pub mod srcref;
pub mod startup;
pub mod strdup;
pub mod strncasecmp;
pub mod subassign;
pub mod subscript;
pub mod subset;
pub mod summary;
pub mod sysutils;
pub mod times;
pub mod unique;
pub mod util_main;
pub mod version;

pub(crate) mod base_wrappers;

#[cfg(test)]
mod sample_contract_test;

#[cfg(feature = "renderplot-device")]
pub(crate) mod portable_plot;

pub(crate) mod loess;

#[cfg(feature = "renderplot-device")]
pub(crate) mod graphics_recording;

#[cfg(feature = "renderplot-device")]
pub(crate) mod graphics_raster;

pub(crate) mod graphics_highlevel;

pub(crate) mod pretty;

#[cfg(feature = "renderplot-device")]
pub(crate) mod plotmath;
#[cfg(feature = "renderplot-device")]
pub(crate) mod portable_grid;
