pf <- function(s) tryCatch({deparse(parse(text=s)[[1]])}, error=function(e) paste("ERR:", conditionMessage(e)))
cat("1:", pf("?\nTRUE"), "\n")
cat("2:", pf("?"), "\n")
cat("3:", pf("1 ?"), "\n")
cat("4:", pf("? a ? b"), "\n")
cat("5:", pf("a ? b ? c"), "\n")
cat("6:", pf("1 ?\n2"), "\n")
cat("7:", pf("x ? "), "\n")
cat("8:", pf("?function(x) x"), "\n")
cat("9:", pf("f(?x)"), "\n")
cat("10:", pf("a ? b + c"), "\n")
cat("11:", pf("-1 ? x"), "\n")
cat("12:", pf("if (TRUE) 1 else 2\n"), "\n")
cat("13:", pf("if (TRUE)\n1\nelse 2\n"), "\n")
cat("14:", deparse(parse(text="if (TRUE) 1 else 2")[[1]]), "\n")
