[package]
name = "r-uniffi"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
uniffi = { version = "0.30.0" }
r-embed = { path = "../r-embed" }
thiserror = { workspace = true }
