import { expect, test } from "@playwright/test"
import { readFile } from "node:fs/promises"
import AxeBuilder from "@axe-core/playwright"

test("focused editor runs R and gallery opens its chosen recipe", async ({
  page,
}) => {
  await page.goto("/editor/")
  await expect(page.locator("h1")).toHaveText("Your space for a little R.")
  await expect(page.locator(".hero")).toHaveCount(0)
  await expect(page.getByAltText("Plot generated by your R code")).toBeVisible({
    timeout: 30000,
  })
  await page.goto("/examples/")
  await expect(page.locator(".example-card")).toHaveCount(18)
  await page
    .getByRole("button", { name: "Try Let R do the algebra", exact: true })
    .click()
  await expect(page).toHaveURL(/\/editor\/\?example=matrix/)
  await expect(page.locator(".console-output")).toContainText("Solution:", {
    timeout: 30000,
  })
})

test("focused pages have footer navigation and accessible mobile layouts", async ({
  page,
}) => {
  await page.setViewportSize({ width: 390, height: 844 })
  for (const path of [
    "console",
    "editor",
    "examples",
    "local-ai",
    "embedding",
    "compatibility",
  ]) {
    await page.goto(`/${path}/`)
    await expect(page.locator("h1")).toHaveCount(1)
    await expect(
      page.getByRole("navigation", { name: "Site map" }).getByRole("link")
    ).toHaveCount(7)
    expect(
      await page.evaluate(() => document.documentElement.scrollWidth)
    ).toBeLessThanOrEqual(390)
    expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
  }
})

test("production pages contain unique metadata and content before JavaScript", async () => {
  const titles = new Set<string>()
  for (const path of [
    "",
    "console/",
    "editor/",
    "examples/",
    "local-ai/",
    "embedding/",
    "compatibility/",
  ]) {
    const html = await readFile(`dist/${path}index.html`, "utf8")
    titles.add(html.match(/<title>(.*?)<\/title>/)![1])
    expect(html).toMatch(/<h1[ >]/)
    expect(html).toContain('aria-label="Site map"')
    expect(html).toMatch(/name="description" content="[^"]+"/)
  }
  expect(titles.size).toBe(7)
  expect(await readFile("dist/404.html", "utf8")).toContain(
    'name="robots" content="noindex"'
  )
})
