import { test, expect } from "@playwright/test"

test("output tabs inspect one execution and an empty console stays disabled", async ({
  page,
}) => {
  await page.goto("/editor/")
  await expect(page.getByAltText("Plot generated by your R code")).toBeVisible({
    timeout: 30000,
  })
  const consoleTab = page.getByRole("button", { name: "Console", exact: true })
  await expect(consoleTab).toBeDisabled()
  await page.locator(".cm-content").click()
  await page.keyboard.press("ControlOrMeta+A")
  await page.keyboard.insertText(
    'counter <- if (exists("counter")) counter + 1 else 1; cat("Execution", counter); plot(1:3)'
  )
  await expect(consoleTab).toBeEnabled({ timeout: 30000 })
  await consoleTab.click()
  await expect(page.locator(".console-output")).toContainText("Execution 1")
  await page.getByRole("button", { name: "Plot", exact: true }).click()
  await expect(page.getByAltText("Plot generated by your R code")).toBeVisible()
  await consoleTab.click()
  // Longer than the old mode-change debounce: switching tabs must not evaluate again.
  await page.waitForTimeout(1000)
  await expect(page.locator(".console-output")).toContainText("Execution 1")
  await expect(page.getByRole("alert")).toHaveCount(0)
})

test("automatic execution keeps quick runs quiet but exposes Stop for a loop", async ({
  page,
}) => {
  await page.goto("/editor/")
  await expect(page.getByAltText("Plot generated by your R code")).toBeVisible({
    timeout: 30000,
  })
  await page.evaluate(() => {
    const seen: string[] = []
    Object.assign(window, { observedStopButtons: seen })
    new MutationObserver(() => {
      if (
        [...document.querySelectorAll("button")].some(
          (b) => b.textContent?.trim() === "Stop"
        )
      )
        seen.push("Stop")
    }).observe(document.body, {
      subtree: true,
      childList: true,
      characterData: true,
    })
  })
  const editor = page.locator(".cm-content")
  await editor.click()
  await page.keyboard.press("ControlOrMeta+A")
  await page.keyboard.insertText("cat(2 + 2)")
  await expect(page.locator(".console-output")).toContainText("4", {
    timeout: 30000,
  })
  expect(
    await page.evaluate(
      () =>
        (window as unknown as { observedStopButtons: string[] })
          .observedStopButtons
    )
  ).toEqual([])
  await editor.click()
  await page.keyboard.press("ControlOrMeta+A")
  await page.keyboard.insertText("while (TRUE) {}")
  await page
    .getByRole("button", { name: "Stop", exact: true })
    .click({ timeout: 10000 })
  await expect(
    page.getByRole("button", { name: "Stop", exact: true })
  ).toHaveCount(0)
})
