import { expect, test } from "@playwright/test"
import AxeBuilder from "@axe-core/playwright"

test("manual mode waits for Run and survives recipe changes", async ({
  page,
}) => {
  await page.goto("/")
  await expect(page.getByAltText("Plot generated by your R code")).toBeVisible({
    timeout: 30000,
  })
  await page.getByRole("combobox", { name: "When to run code" }).click()
  await page.getByRole("option", { name: /Run manually/ }).click()
  await page.getByRole("combobox", { name: "Choose an R example" }).click()
  await page.getByRole("option", { name: "Let R do the algebra" }).click()
  await expect(
    page.getByRole("combobox", { name: "When to run code" })
  ).toContainText("Run manually")
  await page.waitForTimeout(900)
  await expect(page.locator(".console-output")).not.toContainText("Solution:")
  await page.getByRole("button", { name: "Run code", exact: true }).click()
  await expect(page.locator(".console-output")).toContainText("Solution:", {
    timeout: 30000,
  })
  await page.locator(".cm-content").fill("print(12345)")
  await page.waitForTimeout(900)
  await expect(page.locator(".console-output")).not.toContainText("12345")
  await page.getByRole("combobox", { name: "When to run code" }).click()
  await page.getByRole("option", { name: /Run automatically/ }).click()
  await expect(page.locator(".console-output")).toContainText("12345", {
    timeout: 30000,
  })
  await expect(
    page.getByRole("button", { name: "Run code", exact: true })
  ).toHaveCount(0)
})

test("theme follows system until an explicit choice, persists, and has accessible contrast", async ({
  page,
}) => {
  await page.emulateMedia({ colorScheme: "dark" })
  await page.goto("/")
  await expect(page.locator("html")).toHaveClass(/dark/)
  await page.getByRole("button", { name: "Switch to light theme" }).click()
  await expect(page.locator("html")).not.toHaveClass(/dark/)
  await page.reload()
  await expect(page.locator("html")).not.toHaveClass(/dark/)
  await expect(page.getByAltText("Plot generated by your R code")).toBeVisible({
    timeout: 30000,
  })
  for (const dark of [false, true]) {
    if (dark)
      await page.getByRole("button", { name: "Switch to dark theme" }).click()
    await page.waitForTimeout(250)
    const result = await new AxeBuilder({ page }).analyze()
    expect(result.violations).toEqual([])
    for (const width of [320, 390, 604, 1440]) {
      await page.setViewportSize({ width, height: 1000 })
      expect(
        await page.evaluate(() => document.documentElement.scrollWidth)
      ).toBeLessThanOrEqual(width)
    }
  }
  await expect(
    page.locator(".github-link > svg:first-child path")
  ).toHaveAttribute("d", /^M12/)
})

test("copy uses the reference icon animation and one-second feedback", async ({
  page,
}) => {
  await page.goto("/")
  await page.evaluate(() =>
    Object.defineProperty(navigator, "clipboard", {
      value: {
        writeText: async (value: string) => {
          ;(window as Window & { copiedTestValue?: string }).copiedTestValue =
            value
        },
      },
    })
  )
  await page.getByRole("button", { name: "Copy R code", exact: true }).click()
  await expect(page.locator(".copy-icon-swap")).toHaveAttribute(
    "data-copied",
    "true"
  )
  expect(
    await page.evaluate(
      () => (window as Window & { copiedTestValue?: string }).copiedTestValue
    )
  ).toContain("loess")
  await expect(page.locator(".copy-icon-swap")).toHaveAttribute(
    "data-copied",
    "false",
    { timeout: 2000 }
  )
  await expect(page.getByText("⌘ / Ctrl + Enter to run")).toHaveCount(0)
  await page.setViewportSize({ width: 690, height: 1050 })
  await page.locator("#examples").scrollIntoViewIfNeeded()
  const header = await page.locator(".site-header").boundingBox()
  expect(header?.height).toBe(56)
  expect(header?.y).toBe(0)
})
