# Generated by pinned GNU R revision bac583951b728e97b9786804d3b4081f0fe18df5.
# Run: R_DEFAULT_PACKAGES=NULL Rscript --vanilla generate-promises.R <output-directory>
# Both files are uncompressed XDR serialization version 2.
args <- commandArgs(trailingOnly = TRUE)
out <- if (length(args)) args[[1L]] else "."

e <- new.env(hash = FALSE, parent = baseenv())
e$answer <- 7L
e$self <- e
delayedAssign("lazy", answer, eval.env = e, assign.env = e)
delayedAssign("cached", 9L, eval.env = e, assign.env = e)
invisible(e$cached)
saveRDS(e, file.path(out, "gnu-promise-environment-v2.rds"),
        version = 2, compress = FALSE)

persistent <- new.env(parent = emptyenv())
saveRDS(persistent, file.path(out, "gnu-persistent-environment-v2.rds"),
        version = 2, compress = FALSE,
        refhook = function(object) if (is.environment(object)) "env::broken" else NULL)
