# Generated by pinned GNU R revision bac583951b728e97b9786804d3b4081f0fe18df5.
# Copy both original closures while preserving their namespace environments.
original_lm <- stats::lm
original_covratio <- stats::covratio
lm <- eval(call("function", formals(original_lm), body(original_lm)), environment(original_lm))
covratio <- eval(call("function", formals(original_covratio), body(original_covratio)), environment(original_covratio))
stopifnot(identical(body(lm), body(original_lm)), identical(body(covratio), body(original_covratio)))
run <- function(name, y) {
  cat("CASE ", name, "\n", sep="")
  out <- tryCatch({
    fit <- lm(y ~ 1)
    list(coefficients=fit$coefficients, rank=fit$rank, df.residual=fit$df.residual,
      residuals=fit$residuals, fitted.values=fit$fitted.values,
      qr=fit$qr[c("qr", "qraux", "rank", "pivot")],
      na.action=fit$na.action, covratio=covratio(fit))
  }, error=function(e) conditionMessage(e))
  dput(out)
}
run("one", 7)
run("constant", c(3,3,3,3))
run("missing_named", c(a=1,b=NA_real_,c=3,d=NaN,e=5))
run("all_missing", c(NA_real_,NaN))
run("infinite", c(1,Inf,2))
run("zero_response_rank_one", c(0,0,0))
run("integer", c(1L,2L,4L))
