#![allow(non_snake_case, non_upper_case_globals, dead_code, unused_variables)]

//! Port of R's src/main/gram.c — R parser (stub).
//!
//! This module provides stubs for R's expression parser.
//! The real parser is generated by yacc/bison from gram.y.
//!
//! NOTE: gram_ex.rs handles the regex/expression helper functions.
//! This file handles the core parser entry points.

use std::os::raw::{c_char, c_int};

use crate::sexp::constructors::*;
use crate::sexp::ffi::{R_xlen_t, SEXP, SEXPTYPE};
use crate::sexp::globals::R_NilValue;

// ---------------------------------------------------------------------------
// Parse status constants
// ---------------------------------------------------------------------------

pub const PARSE_OK: c_int = 1;
pub const PARSE_INCOMPLETE: c_int = 2;
pub const PARSE_ERROR: c_int = 4;
pub const PARSE_EOF: c_int = 8;

// ---------------------------------------------------------------------------
// R_ParseVector — parse text into R expressions
// ---------------------------------------------------------------------------

/// Parse a character vector of R code into a list of expressions.
pub unsafe fn R_ParseVector(_text: SEXP, _n: c_int, _status: *mut c_int, _srcfile: SEXP) -> SEXP {
    unsafe {
        // Stub: return empty expression list
        if !_status.is_null() {
            *_status = PARSE_OK;
        }
        Rf_allocVector(SEXPTYPE::EXPRSXP.0, 0)
    }
}

// ---------------------------------------------------------------------------
// R_ParseEvalString — parse and evaluate a string
// ---------------------------------------------------------------------------

/// Parse and evaluate a string of R code.
pub unsafe fn R_ParseEvalString(_s: *const c_char, _envir: SEXP) -> SEXP {
    unsafe { R_NilValue() }
}

// ---------------------------------------------------------------------------
// R_ParseEval — parse and evaluate a string with completion handler
// ---------------------------------------------------------------------------

/// Parse and evaluate a string of R code with completion.
pub unsafe fn R_ParseEval(_s: *const c_char, _envir: SEXP) -> SEXP {
    unsafe { R_NilValue() }
}

// ---------------------------------------------------------------------------
// R_ParseEvalBuffer — parse and evaluate a buffer
// ---------------------------------------------------------------------------

/// Parse and evaluate a buffer of R code.
pub unsafe fn R_ParseEvalBuffer(_buf: *const c_char, _len: c_int, _envir: SEXP) -> SEXP {
    unsafe { R_NilValue() }
}

// ---------------------------------------------------------------------------
// R_CurrentParseLine — current parse line number
// ---------------------------------------------------------------------------

/// Get the current parse line number.
pub unsafe fn R_CurrentParseLine() -> c_int {
    0
}

// ---------------------------------------------------------------------------
// R_ParseFilename — get the current parse filename
// ---------------------------------------------------------------------------

/// Get the current parse filename.
pub unsafe fn R_ParseFilename() -> *const c_char {
    static EMPTY: [c_char; 1] = [0];
    EMPTY.as_ptr()
}

// ---------------------------------------------------------------------------
// R_ParseContext — parse context management
// ---------------------------------------------------------------------------

/// Enter a new parse context.
pub unsafe fn R_ParseContext(_buf: *const c_char, _len: c_int) -> c_int {
    0
}

/// End the current parse context.
pub unsafe fn R_ParseContextEnd() {}

// ---------------------------------------------------------------------------
// R_ParseVectorBuffer — parse from buffer
// ---------------------------------------------------------------------------

/// Parse from a character buffer.
pub unsafe fn R_ParseVectorBuffer(
    _text: *const c_char,
    _len: R_xlen_t,
    _n: c_int,
    _status: *mut c_int,
    _srcfile: SEXP,
) -> SEXP {
    unsafe {
        if !_status.is_null() {
            *_status = PARSE_OK;
        }
        Rf_allocVector(SEXPTYPE::EXPRSXP.0, 0)
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use std::ptr;

    use super::*;

    #[test]
    fn test_parse_status_constants() {
        assert!(PARSE_OK > 0);
        assert!(PARSE_INCOMPLETE > 0);
        assert!(PARSE_ERROR > 0);
        assert!(PARSE_EOF > 0);
    }

    #[test]
    fn test_parse_vector_stub() {
        unsafe {
            let mut status: c_int = 0;
            let result = R_ParseVector(ptr::null_mut(), 1, &mut status, ptr::null_mut());
            assert_eq!(status, PARSE_OK);
            assert!(!result.is_null());
        }
    }

    #[test]
    fn test_parse_eval_string_stub() {
        unsafe {
            let result = R_ParseEvalString(ptr::null(), ptr::null_mut());
            assert_eq!(result, R_NilValue());
        }
    }

    #[test]
    fn test_current_parse_line() {
        unsafe {
            assert_eq!(R_CurrentParseLine(), 0);
        }
    }

    #[test]
    fn test_parse_filename() {
        unsafe {
            let s = R_ParseFilename();
            assert!(!s.is_null());
        }
    }
}
