# Independently generated by the exact oracle in oracle/r-oracle.json, r90451.
args <- commandArgs(TRUE)
stopifnot(length(args) == 1L, R.version[["svn rev"]] == "90451")
dir.create(args[[1L]], recursive=TRUE, showWarnings=FALSE)
frame <- data.frame(value=c(1.25, NA_real_),
                    group=factor(c("b", "a"), levels=c("a", "b")),
                    date=as.Date(c("2000-01-01", "2001-02-03")),
                    row.names=c("first", "second"))
shared_a <- new.env(parent=emptyenv())
shared_a$value <- 37L
shared_a$self <- shared_a
shared_b <- shared_a
null_value <- NULL
named_na <- c(first=NA_integer_, second=9L)
for (version in 2:3) {
  save(frame, shared_a, shared_b, null_value, named_na,
       file=file.path(args[[1L]], paste0("workspace-v", version, ".rda")),
       version=version, compress=FALSE)
}
save(frame, shared_a, shared_b, null_value, named_na,
     file=file.path(args[[1L]], "workspace-gzip.rda"),
     version=3, compress="gzip")
for (compression in c("bzip2", "xz")) {
  save(frame, shared_a, shared_b, null_value, named_na,
       file=file.path(args[[1L]], paste0("workspace-", compression, ".rda")),
       version=3, compress=compression)
}
save(frame, shared_a, shared_b, null_value, named_na,
     file=file.path(args[[1L]], "workspace-ascii.rda"),
     version=3, ascii=TRUE, compress=FALSE)
cat("saved names:", paste(c("frame", "shared_a", "shared_b", "null_value", "named_na"), collapse=","), "\n")
for (file in list.files(args[[1L]], pattern="[.]rda$", full.names=TRUE)) {
  target <- new.env(parent=emptyenv())
  loaded <- load(file, target)
  stopifnot(identical(loaded, c("frame", "shared_a", "shared_b", "null_value", "named_na")),
            identical(target$frame, frame), identical(target$shared_a, target$shared_b),
            identical(target$shared_a, target$shared_a$self),
            identical(target$null_value, NULL), identical(target$named_na, named_na))
  cat(basename(file), "round trip complete\n")
}
