x <- c(1.2, 0.8, 1.1, 0.5, 0.9, 1.4, 0.7, 1.0, 0.6, 1.3, 0.85, 1.15)
a <- arima(x, order = c(2, 0, 0), method = "CSS")
cat(paste(round(as.numeric(a$coef), 4), collapse = ","), "\n", sep = "")
cat(sprintf("%.4f", a$sigma2), "\n", sep = "")
b <- arima(x, order = c(0, 1, 0), method = "CSS")
cat(length(b$coef), "\n", sep = "")
cat(sprintf("%.4f", b$sigma2), "\n", sep = "")
c <- arima(x, order = c(1, 1, 0), method = "CSS")
cat(sprintf("%.3f", as.numeric(c$coef)), "\n", sep = "")
