x <- c(3, 1, 2)
y <- c(3, 1, 2)
k <- ksmooth(x, y, kernel = "box", bandwidth = 1, x.points = c(2, 1, 3))
cat(paste(sprintf("%.1f", k$x), collapse = ","), "\n", sep = "")
k2 <- ksmooth(x, y, kernel = "box", bandwidth = 1, range.x = c(1, 2), n.points = 3)
cat(sprintf("%.2f", k2$x[1]), "\n", sep = "")
cat(sprintf("%.2f", k2$x[3]), "\n", sep = "")
cat(length(k2$x), "\n", sep = "")
set.seed(1)
cat(sprintf("%.5f", rf(1, df2 = 8, df1 = 4)), "\n", sep = "")
set.seed(1)
cat(sprintf("%.5f", rf(1, 4, 8)), "\n", sep = "")
