set.seed(1)
a <- rnorm(1, 0, mean = 10)
set.seed(1)
b <- rnorm(1, mean = 10, sd = 0)
cat(identical(a, b), "\n", sep = "")
cat(sprintf("%.8f", a), "\n", sep = "")
set.seed(1)
cat(sprintf("%.8f", rnorm(mean = 10, n = 1, sd = 0)), "\n", sep = "")
set.seed(1)
cat(sprintf("%.8f", rnorm(1, s = 0)), "\n", sep = "")
set.seed(1)
cat(sprintf("%.8f", do.call(rnorm, list(1, 0, mean = 10))), "\n", sep = "")
set.seed(1)
cat(sprintf("%.5f", rgamma(1, scale = 2, shape = 3)), "\n", sep = "")
set.seed(1)
cat(sprintf("%.5f", rnbinom(1, mu = 4, size = 2)), "\n", sep = "")
set.seed(1)
cat(sprintf("%.5f", rexp(rate = 2, n = 1)), "\n", sep = "")
tryCatch(rnorm(1, foo = 2), error = function(e) cat(conditionMessage(e), "\n", sep = ""))
tryCatch(rnorm(1, mean = 1, mean = 2), error = function(e) cat(conditionMessage(e), "\n", sep = ""))
tryCatch(rnorm(1, m = 1, mean = 2), error = function(e) cat(conditionMessage(e), "\n", sep = ""))
