m0 <- matrix(pi, 0, 3)
a302 <- array("", dim = c(3, 0, 2))
cat(identical(apply(m0, 1, dim), NULL), "\n", sep = "")
cat(identical(apply(m0, 2, dim), NULL), "\n", sep = "")
cat(identical(apply(m0, 1, length), integer(0)), "\n", sep = "")
cat(identical(apply(m0, 2, length), integer(3)), "\n", sep = "")
cat(identical(apply(a302, 1, mode), rep("character", 3)), "\n", sep = "")
aa <- apply(a302, 2, mode)
cat(is.character(aa) && length(aa) == 0, "\n", sep = "")
cat(paste(dim(a302), collapse = ","), "\n", sep = "")
cat(identical(apply(a302, 3, mode), rep("character", 2)), "\n", sep = "")
cat(paste(dim(a302), collapse = ","), "\n", sep = "")
cat(identical(apply(a302, 3, length), integer(2)), "\n", sep = "")
cat(identical(apply(a302, 3, dim), matrix(as.integer(c(3, 0)), 2, 2)), "\n", sep = "")
cat(identical(apply(a302, 1, dim), matrix(as.integer(c(0, 2)), 2, 3)), "\n", sep = "")
cat(identical(apply(array(dim = 3), 1, length), rep(1:1, 3)), "\n", sep = "")
cat(identical(apply(array(dim = 0), 1, length), rep(1:1, 0)), "\n", sep = "")
