set.seed(1)
a <- rnorm(1, 0, mean = 10)
set.seed(1)
b <- rnorm(1, mean = 10, sd = 0)
stopifnot(identical(a, b))
set.seed(1)
c <- rnorm(n = 1, sd = 1, mean = 0)
set.seed(1)
d <- rnorm(1)
stopifnot(identical(c, d))
cat(a, "\n", sep = "")
cat(identical(a, b), "\n", sep = "")
cat(identical(c, d), "\n", sep = "")
