d <- str(3.14)
d <- str(5L)
d <- str(TRUE)
d <- str("Abc")
d <- str(c("Abc", "Bde"))
d <- str(1:3)
d <- str(c(1.5, 2.5))
d <- str(c(TRUE, FALSE))
d <- str(1 + 2i)
d <- str(as.raw(1:2))
d <- str(character(0))
d <- str(integer(0))
