x <- c("a", NA, "b")
fx <- factor(x, exclude = "")
cat(paste(levels(fx), collapse = "|"), "\n", sep = "")
cat(nlevels(fx), "\n", sep = "")
cat(is.na(levels(fx)), "\n")
cat(paste(as.character(fx), collapse = "|"), "\n", sep = "")

r <- capture.output(print(fx))
cat(r[2], "\n", sep = "")
fy <- factor(x)
cat(paste(levels(fy), collapse = "|"), "\n", sep = "")
cat(nlevels(fy), "\n", sep = "")
fz <- factor(x, exclude = NULL)
cat(nlevels(fz), "\n", sep = "")
