f <- tempfile()
g <- tempfile()
h <- tempfile()
cat("abc", file = f)
print(as.logical(file.access(f, 0) == 0))
print(as.logical(file.access(paste0(f, "-missing"), 0) == -1))
print(file.copy(f, h))
print(suppressWarnings(readLines(h)))
print(file.rename(f, g))
print(file.exists(c(f, g)))
print(file.remove(g, h))
print(file.exists(c(g, h)))
