print(length(integer()))
print(integer(3))
print(logical(3))
print(numeric(2))
print(character(2))
print(complex(2))
print(raw(2))
v <- vector("list", 2)
print(length(v))
print(is.null(v[[1]]))
print(vector(mode = "character", length = 2))
print(length(vector(length = 2, mode = "integer")))
