root <- file.path(tempdir(), "rport-list-files")
unlink(root, recursive = TRUE)
dir.create(file.path(root, "dir", "sub"), recursive = TRUE)
cat("a", file = file.path(root, "a.txt"))
cat("b", file = file.path(root, "b.R"))
cat("A", file = file.path(root, "A.md"))
cat("h", file = file.path(root, ".hidden"))
cat("c", file = file.path(root, "dir", "c.txt"))

print(paste(list.files(root), collapse = ","))
print(paste(list.files(root, all.files = TRUE), collapse = ","))
print(paste(list.files(root, all.files = TRUE, no.. = TRUE), collapse = ","))
print(paste(list.files(root, pattern = "\\.txt$"), collapse = ","))
print(paste(list.files(root, pattern = "^A", ignore.case = TRUE), collapse = ","))
print(paste(list.files(root, recursive = TRUE), collapse = ","))
print(paste(list.files(root, recursive = TRUE, include.dirs = TRUE), collapse = ","))
