d <- date()
print(is.character(d))
print(length(d))
print(nchar(d))
print(substr(d, 4, 4) == " ")
print(substr(d, 8, 8) == " ")
print(substr(d, 11, 11) == " ")
print(substr(d, 14, 14) == ":")
print(substr(d, 17, 17) == ":")
print(substr(d, 20, 20) == " ")
