m <- matrix(1:6, 2, 3)
rows <- asplit(m, 1)
print(length(rows))
print(dim(rows))
print(rows[[1]])
print(dim(rows[[1]]))
print(rows[[2]])

cols <- asplit(m, 2)
print(length(cols))
print(dim(cols))
print(cols[[1]])
print(cols[[3]])

x <- array(1:8, c(2, 2, 2))
by_first_two <- asplit(x, -3)
print(length(by_first_two))
print(dim(by_first_two))
print(by_first_two[[1]])
print(dim(by_first_two[[1]]))
print(by_first_two[[4]])
