p <- tempfile()
con <- file(p, "w")
print(isOpen(con))
writeLines("abc", con)
flush(con)
print(file.exists(p))
close(con)
print(tryCatch(isOpen(con), error = function(e) conditionMessage(e)))
print(readLines(p))
invisible(unlink(p))
