print(is.unsorted(c("a", "b")))
print(is.unsorted(c("b", "a")))
print(is.unsorted(c("a", NA, "b")))
print(is.unsorted(c("a", NA, "b"), na.rm = TRUE))
print(is.unsorted(c(1, 1), strictly = FALSE))
print(is.unsorted(c(1, 1), strictly = TRUE))
print(is.unsorted(c(TRUE, FALSE)))
print(is.unsorted(c(FALSE, TRUE)))
print(is.unsorted(c(1 + 2i, 1 + 1i)))
print(is.unsorted(as.raw(c(2, 1))))
