f <- tempfile(fileext = ".gz")
con <- gzfile(f, "wb")
writeLines(c("alpha", "beta"), con)
close(con)
print(paste(readLines(gzfile(f, "rb")), collapse = "/"))
con <- gzfile(f, "ab")
writeLines("gamma", con)
close(con)
print(paste(readLines(gzfile(f, "rb")), collapse = "/"))
invisible(unlink(f))
