f <- tempfile(fileext = ".bz2")
con <- bzfile(f, "wb")
writeLines(c("red", "blue"), con)
close(con)
print(paste(readLines(bzfile(f, "rb")), collapse = "/"))
con <- bzfile(f, "ab")
writeLines("green", con)
close(con)
print(paste(readLines(bzfile(f, "rb")), collapse = "/"))
invisible(unlink(f))
