f <- tempfile(fileext = ".xz")
con <- xzfile(f, "wb")
writeLines(c("north", "south"), con)
close(con)
print(paste(readLines(xzfile(f, "rb")), collapse = "/"))
con <- xzfile(f, "ab")
writeLines("east", con)
close(con)
print(paste(readLines(xzfile(f, "rb")), collapse = "/"))
invisible(unlink(f))
