d <- as.Date("2020-02-03")
print(d + 1)
print(1 + d)
print(d - 1)

delta <- d - as.Date("2020-02-01")
print(delta)
print(class(delta))
print(attr(delta, "units"))

one_day <- structure(1, units = "days", class = "difftime")
twelve_hours <- structure(12, units = "hours", class = "difftime")
two_days <- structure(2, units = "days", class = "difftime")
print(d + one_day)
print(one_day + d)
print(d + twelve_hours)
print(d - two_days)

print(tryCatch(d + d, error = function(e) conditionMessage(e)))
print(tryCatch(2 - d, error = function(e) conditionMessage(e)))
print(tryCatch(d * 2, error = function(e) conditionMessage(e)))
print(tryCatch(d - structure(1, class = "foo"), error = function(e) conditionMessage(e)))
