show <- function(x) cat(paste(x, collapse = "|"), "\n", sep = "")
show(sort(c("b", NA, "a")))
show(sort(c("b", NA, "a"), na.last = TRUE))
show(sort(c("b", NA, "a"), na.last = FALSE))
show(sort(c("b", NA, "a"), decreasing = TRUE, na.last = TRUE))
show(sort(c(2, NA, 1)))
show(sort(c(2, NA, 1), na.last = TRUE))
show(sort(c(2, NA, 1), na.last = FALSE))
show(sort(c(TRUE, NA, FALSE), na.last = TRUE))
