print(length(ifelse(TRUE, 1:3, 4:6)))
print(ifelse(TRUE, 1:3, 4:6))
print(ifelse(c(TRUE, FALSE), 1:3, 4:6))
cat(typeof(ifelse(logical(0), 1, 2)), length(ifelse(logical(0), 1, 2)), "\n")
cat(typeof(ifelse(logical(0), "yes", "no")), length(ifelse(logical(0), "yes", "no")), "\n")
print(ifelse(TRUE, integer(0), 1L))
print(typeof(ifelse(TRUE, integer(0), 1L)))
print(ifelse(c(TRUE, FALSE), integer(0), 1L))
print(ifelse(c(TRUE, FALSE), "yes", character(0)))
