show <- function(x) cat(paste(x, collapse = "|"), "\n", sep = "")
show(sort.list(c(3, NA, 1)))
show(sort.list(c(3, NA, 1), na.last = FALSE))
show(sort.list(c(3, NA, 1), na.last = NA))
show(sort.list(c(3, NA, 1), decreasing = TRUE))
show(sort.list(c("b", NA, "a")))
show(sort.list(c("b", NA, "a"), na.last = FALSE))
show(sort.list(c("b", NA, "a"), na.last = NA))
show(sort.list(c(TRUE, NA, FALSE), na.last = TRUE))
