print(unique(c("b", "a", "b", NA, NA)))
print(unique(c("b", "a", "b", NA, NA), fromLast = TRUE))
print(unique(c(TRUE, FALSE, TRUE, NA, NA)))
print(unique(c(1, 2, 1, NA, NA), incomparables = NA))
u <- unique(c("a", "b", "a", NA, NA), incomparables = NA)
print(length(u))
print(is.na(u))
print(unique(c(NaN, NaN, NA_real_, NA_real_)))
print(unique(c(NaN, NA_real_, NaN), fromLast = TRUE))
