u <- union(c("b", "a"), c("a", NA, "c"))
print(length(u))
print(u[1:2])
print(is.na(u[3]))
print(u[4])
print(intersect(c("b", "a", NA), c(NA, "b")))
print(setdiff(c("b", "a", NA, "b"), c("a")))
print(setequal(c("b", "a", NA, "b"), c(NA, "a", "b")))
print(setequal(c("b", "a"), c("a", "c")))
