x <- c(a = "x", b = NA, c = "z")
omit <- na.omit(x)
print(as.vector(omit))
print(names(omit))
print(as.integer(attr(omit, "na.action")))
print(names(attr(omit, "na.action")))
print(class(attr(omit, "na.action")))

exclude <- na.exclude(x)
print(as.vector(exclude))
print(names(exclude))
print(as.integer(attr(exclude, "na.action")))
print(names(attr(exclude, "na.action")))
print(class(attr(exclude, "na.action")))
