print(nchar(character(0)))
print(typeof(nchar(character(0))))
print(substr(character(0), 1, 1))
print(typeof(substr(character(0), 1, 1)))
print(trimws(character(0)))
print(typeof(trimws(character(0))))
print(startsWith(character(0), "a"))
print(typeof(startsWith(character(0), "a")))
print(endsWith(character(0), "a"))
print(typeof(endsWith(character(0), "a")))
