print(charmatch(character(0), c("a", "b")))
print(charmatch(c("a", "b"), c("a", "ba")))
print(charmatch(c("", "a", "z"), c("abc", "abd", "")))
print(charmatch(c(NA, "a"), c("a", NA)))
print(charmatch("a", c("a", "a")))
print(charmatch("a", c("ab", "ac")))
print(charmatch("a", c("ab")))
print(charmatch("a", character(0)))
print(charmatch("a", character(0), nomatch = 0L))
