print(pmatch(character(0), c("a", "b")))
print(pmatch(c("a", "b"), c("a", "ba")))
print(pmatch(c("", "a", "z"), c("abc", "abd", "")))
print(pmatch(c(NA, "a"), c("a", NA)))
print(pmatch(c("a", "a"), c("a")))
print(pmatch(c("a", "a"), c("a"), duplicates.ok = TRUE))
print(pmatch("a", c("ab", "ac")))
print(pmatch("a", c("ab")))
print(pmatch("a", character(0)))
print(pmatch("a", character(0), nomatch = 0L))
print(pmatch("", ""))
