print(dpois(numeric(0), 1))
print(ppois(numeric(0), 1))
print(dbinom(numeric(0), 1, 0.5))
print(pbeta(numeric(0), 1, 1))
print(dt(numeric(0), 1))
print(qt(numeric(0), 1))
print(df(numeric(0), 1, 1))
print(qhyper(numeric(0), 1, 1, 1))
print(ptukey(numeric(0), 2, 1))
