r <- regexpr("a", character(0), fixed = TRUE)
print(r)
print(attr(r, "match.length"))
print(attr(r, "index.type"))
print(attr(r, "useBytes"))
print(gregexpr("a", character(0), fixed = TRUE))
print(regexec("a", character(0), fixed = TRUE))
print(grepl("a", character(0), fixed = TRUE))
print(grep("a", character(0), fixed = TRUE))
