print(paste())
print(paste0())
print(paste(collapse = ","))
print(paste0(collapse = ","))
print(paste(character(0)))
print(paste0(character(0)))
print(paste(character(0), character(0)))
print(paste(character(0), character(0), collapse = ","))
print(paste(character(0), "x"))
print(paste0(character(0), "x"))
print(paste("x", character(0)))
print(paste0("x", character(0)))
print(paste(c("a", "b"), character(0)))
print(paste(c("a", "b"), character(0), collapse = ","))
