show <- function(x) {
  cat(paste(dim(x), collapse = "x"), typeof(x), "\n")
}
show(cbind(integer(0)))
show(rbind(integer(0)))
show(cbind(integer(0), 1:2))
print(cbind(integer(0), 1:2))
show(rbind(integer(0), 1:2))
print(rbind(integer(0), 1:2))
show(cbind(integer(0), numeric(0)))
show(rbind(integer(0), numeric(0)))
show(cbind(a = integer(0)))
dn <- dimnames(cbind(a = integer(0)))
print(is.null(dn[[1]]))
print(dn[[2]])
show(rbind(a = integer(0)))
dn <- dimnames(rbind(a = integer(0)))
print(dn[[1]])
print(is.null(dn[[2]]))
