f <- tempfile()
writeLines(c("123", "456"), f)
x <- read.fwf(f, widths = 0L)
cat(paste(names(x), collapse = ","), "\n", sep = "")
print(is.na(x[[1]]))
x <- read.fwf(f, widths = c(1, 0, 2))
cat(paste(names(x), collapse = ","), "\n", sep = "")
print(x[[1]])
print(is.na(x[[2]]))
print(x[[3]])

f <- tempfile()
writeLines(c("123456", "789012"), f)
x <- read.fwf(f, widths = c(-2, 2))
cat(paste(names(x), collapse = ","), "\n", sep = "")
print(x[[1]])
x <- read.fwf(f, widths = c(2, -2, 2))
cat(paste(names(x), collapse = ","), "\n", sep = "")
print(x[[1]])
print(x[[2]])
