print(exists("version"))
print(exists("version", mode = "function"))
print(exists("R.version"))
print(exists("R.version", mode = "function"))
print(exists("R.version.string"))
print(exists("R.version.string", mode = "function"))
print(identical(version, R.version))
print(typeof(version))
print(typeof(R.version.string))
print(length(R.version.string))
print(is.list(R.Version()))
print(typeof(getRversion()))
