print(exists("is_interactive"))
print(exists("is_interactive", mode = "function"))
print(exists("which_array"))
print(exists("which_array", mode = "function"))
print(exists("cat_args"))
print(exists("cat_args", mode = "function"))
print(exists("message_args"))
print(exists("message_args", mode = "function"))
print(exists("UseMethod", mode = "function"))
print(exists("useMethod"))
print(exists("useMethod", mode = "function"))
