print(exists("list.get"))
print(exists("list.set"))
print(exists("S3_class"))
print(exists("set_slot"))
print(exists("containsClass"))
print(exists("isMethod"))
print(exists("setClass", mode = "function"))
print(exists("slot", mode = "function"))
print(exists("isGeneric", mode = "function"))
