print(exists("str_pad"))
print(exists("str_count"))
print(exists("str_replace"))
print(exists("str_locate"))
print(exists("str_locate_all"))
print(exists("str_sub"))
print(exists("str_sub_all"))
print(exists("allNA"))
print(exists("anyNaN"))
print(exists("allNaN"))
print(exists("splice"))
print(exists("flatten"))
print(exists("melt"))
print(exists("cast"))
print(exists("startsWith", mode = "function"))
print(exists("anyNA", mode = "function"))
print(exists("modifyList", mode = "function"))
print(exists("split", mode = "function"))
