print(exists("cat_enhanced"))
print(exists("message_enhanced"))
print(exists("warning_enhanced"))
print(exists("set_parent.env"))
print(exists("env_name"))
print(exists("is_empty"))
print(exists("mclapply"))
print(exists("future_lapply"))
print(exists("foreach"))
print(exists("restarts"))
print(exists("setattr"))
print(exists("as.list.generic"))
print(exists("cat", mode = "function"))
print(exists("message", mode = "function"))
print(exists("warning", mode = "function"))
print(exists("parent.env", mode = "function"))
print(exists("environmentName", mode = "function"))
print(exists("computeRestarts", mode = "function"))
print(exists("attr<-", mode = "function"))
print(exists("as.list", mode = "function"))
