print(exists("print.integer"))
print(exists("print.integer", mode = "function"))
print(exists("print.numeric"))
print(exists("print.numeric", mode = "function"))
print(exists("print.logical"))
print(exists("print.logical", mode = "function"))
print(exists("print.character"))
print(exists("print.character", mode = "function"))
print(exists("print.complex"))
print(exists("print.complex", mode = "function"))
print(exists("print.environment"))
print(exists("print.environment", mode = "function"))
print(exists("print.formula"))
print(exists("print.formula", mode = "function"))
print(exists("print.call"))
print(exists("print.call", mode = "function"))
print(exists("print.pairlist"))
print(exists("print.pairlist", mode = "function"))
print(exists("print.raw"))
print(exists("print.raw", mode = "function"))
print(exists("summary.numeric"))
print(exists("summary.numeric", mode = "function"))
print(exists("summary.integer"))
print(exists("summary.integer", mode = "function"))
print(exists("summary.logical"))
print(exists("summary.logical", mode = "function"))
print(exists("summary.character"))
print(exists("summary.character", mode = "function"))
print(exists("print.function", mode = "function"))
print(exists("summary.default", mode = "function"))
