s1 <- split(1:4, c("b", "a", "b", "a"))
print(names(s1))
print(unname(s1$a))
print(unname(s1$b))
s2 <- split(c(x = 10, y = 20, z = 30), c("g1", "g1", NA))
print(names(s2))
print(s2$g1)
s3 <- split(c("x", "y", "z"), c(1L, 1L, 2L))
print(names(s3))
print(unname(s3[["1"]]))
print(unname(s3[["2"]]))
s4 <- split(list(1, 2, 3), c("a", "a", "b"))
print(names(s4))
print(unname(lengths(s4)))
print(unlist(s4, use.names = FALSE))
f <- factor(c("a", "a"), levels = c("a", "b"))
s5 <- split(1:2, f)
print(names(s5))
print(unname(s5$a))
print(unname(s5$b))
s6 <- split(1:4, c("a", "b"))
print(unname(s6$a))
print(unname(s6$b))
s7 <- split(1:2, c(10L, 2L))
print(paste(names(s7), collapse = ","))
s8 <- split(1:2, c(TRUE, FALSE))
print(paste(names(s8), collapse = ","))
