show <- function(x) cat(paste(x, collapse = "|"), "\n", sep = "")
show(.Internal(radixsort(TRUE, c(FALSE), FALSE, TRUE, c("b", "a", "c", "a"))))
show(.Internal(radixsort(TRUE, c(TRUE), FALSE, TRUE, c("b", "a", "c", "a"))))
show(.Internal(radixsort(FALSE, c(FALSE), FALSE, TRUE, c("b", NA, "a"))))
show(.Internal(radixsort(NA, c(FALSE), FALSE, TRUE, c("b", NA, "a"))))
g <- .Internal(radixsort(TRUE, c(FALSE), TRUE, TRUE, c("b", "a", "a", "c")))
show(g)
show(attr(g, "ends"))
print(attr(g, "maxgrpn"))
print(class(g))
