f <- tempfile()
x <- c(1L, 2L, NA_integer_)
y <- c("a", NA_character_, "b")
.Internal(save(c("x", "y"), f, TRUE, NULL, .GlobalEnv, TRUE))
rm(x, y)
print(.Internal(load(f, .GlobalEnv)))
cat(paste(x, collapse = "|"), "\n", sep = "")
cat(paste(is.na(y), collapse = "|"), "\n", sep = "")
cat(paste(y[!is.na(y)], collapse = "|"), "\n", sep = "")
