f <- tempfile()
x <- c(1L, 2L, NA_integer_)
y <- c("a", NA_character_, "b")
save(x, y, file = f, ascii = TRUE)
rm(x, y)
print(load(f, envir = .GlobalEnv))
cat(paste(x, collapse = "|"), "\n", sep = "")
cat(paste(is.na(y), collapse = "|"), "\n", sep = "")
cat(paste(y[!is.na(y)], collapse = "|"), "\n", sep = "")
