f <- tempfile()
z <- list(c(1L, NA_integer_), c("a", NA_character_), list(TRUE, 2.5))
save(z, file = f, ascii = TRUE)
rm(z)
print(load(f, envir = .GlobalEnv))
print(z[[1]])
cat(paste(is.na(z[[2]]), collapse = "|"), "\n", sep = "")
cat(paste(z[[2]][!is.na(z[[2]])], collapse = "|"), "\n", sep = "")
print(z[[3]][[1]])
print(z[[3]][[2]])
