f <- tempfile()
x <- c(alpha = 1L, beta = NA_integer_)
z <- list(first = c(a = "x", b = NA_character_), second = list(inner = 2.5))
save(x, z, file = f, ascii = TRUE)
rm(x, z)
cat(paste(load(f, envir = .GlobalEnv), collapse = "|"), "\n", sep = "")
cat(paste(names(x), collapse = "|"), "\n", sep = "")
cat(paste(x, collapse = "|"), "\n", sep = "")
cat(paste(names(z), collapse = "|"), "\n", sep = "")
cat(paste(names(z[[1]]), collapse = "|"), "\n", sep = "")
cat(paste(names(z[[2]]), collapse = "|"), "\n", sep = "")
