f <- tempfile()
m <- matrix(1:6, 2, 3)
a <- array(c("a", NA_character_, "b", "c"), c(2, 2))
save(m, a, file = f, ascii = TRUE)
rm(m, a)
cat(paste(load(f, envir = .GlobalEnv), collapse = "|"), "\n", sep = "")
cat(paste(dim(m), collapse = "|"), "\n", sep = "")
cat(paste(as.vector(m), collapse = "|"), "\n", sep = "")
cat(paste(dim(a), collapse = "|"), "\n", sep = "")
cat(paste(is.na(as.vector(a)), collapse = "|"), "\n", sep = "")
