f <- tempfile()
g <- factor(c("b", "a", NA, "b"), levels = c("a", "b"))
save(g, file = f, ascii = TRUE)
rm(g)
cat(paste(load(f, envir = .GlobalEnv), collapse = "|"), "\n", sep = "")
cat(paste(class(g), collapse = "|"), "\n", sep = "")
cat(paste(levels(g), collapse = "|"), "\n", sep = "")
cat(paste(as.character(g), collapse = "|"), "\n", sep = "")
cat(paste(is.na(g), collapse = "|"), "\n", sep = "")
