f <- tempfile()
m <- matrix(1:4, 2, 2)
dimnames(m) <- list(c("r1", "r2"), c("c1", "c2"))
save(m, file = f, ascii = TRUE)
rm(m)
cat(paste(load(f, envir = .GlobalEnv), collapse = "|"), "\n", sep = "")
cat(paste(dimnames(m)[[1]], collapse = "|"), "\n", sep = "")
cat(paste(dimnames(m)[[2]], collapse = "|"), "\n", sep = "")
cat(paste(as.vector(m), collapse = "|"), "\n", sep = "")
