f <- tempfile()
df <- data.frame(a = 1:2, b = c("x", "y"))
save(df, file = f, ascii = TRUE)
rm(df)
cat(paste(load(f, envir = .GlobalEnv), collapse = "|"), "\n", sep = "")
cat(paste(class(df), collapse = "|"), "\n", sep = "")
cat(paste(names(df), collapse = "|"), "\n", sep = "")
cat(paste(row.names(df), collapse = "|"), "\n", sep = "")
cat(paste(df$a, collapse = "|"), "\n", sep = "")
cat(paste(as.character(df$b), collapse = "|"), "\n", sep = "")
