f <- tempfile()
z <- c(1+2i, NA_complex_, Inf-3i)
rawv <- as.raw(c(0, 15, 255))
names(z) <- c("a", "b", "c")
names(rawv) <- c("zero", "mid", "max")
save(z, rawv, file = f, ascii = TRUE)
rm(z, rawv)
cat(paste(load(f, envir = .GlobalEnv), collapse = "|"), "\n", sep = "")
cat(paste(names(z), collapse = "|"), "\n", sep = "")
print(unname(z))
cat(paste(names(rawv), collapse = "|"), "\n", sep = "")
print(unname(rawv))
