f <- tempfile()
expr <- expression(a = 1L, b = "x", c = TRUE, d = 2.5, e = 1 + 2, f = quote(foo(bar = 3)))
save(expr, file = f, ascii = TRUE)
rm(expr)
cat(paste(load(f, envir = .GlobalEnv), collapse = "|"), "\n", sep = "")
cat(paste(names(expr), collapse = "|"), "\n", sep = "")
cat(typeof(expr), "\n", sep = "")
cat(paste(vapply(as.list(expr), typeof, ""), collapse = "|"), "\n", sep = "")
cat(paste(vapply(as.list(expr)[5:6], deparse, ""), collapse = "|"), "\n", sep = "")
invisible(unlink(f))
