f <- tempfile()
pl <- pairlist(alpha = 1L, beta = "x", gamma = TRUE, delta = 2.5)
pl2 <- as.pairlist(list(one = 1L, two = "y"))
cat(typeof(pl2), "\n", sep = "")
cat(paste(names(as.list(pl2)), collapse = "|"), "\n", sep = "")
save(pl, file = f, ascii = TRUE)
rm(pl)
cat(paste(load(f, envir = .GlobalEnv), collapse = "|"), "\n", sep = "")
cat(typeof(pl), "\n", sep = "")
cat(paste(names(pl), collapse = "|"), "\n", sep = "")
cat(length(pl), "\n", sep = "")
cat(paste(vapply(as.list(pl), typeof, ""), collapse = "|"), "\n", sep = "")
invisible(unlink(f))
