f <- tempfile()
pl <- formals(function(alpha = 1L, beta = "x", gamma = TRUE, delta = 2.5) NULL)
save(pl, file = f, ascii = TRUE)
rm(pl)
cat(paste(load(f, envir = .GlobalEnv), collapse = "|"), "\n", sep = "")
cat(typeof(pl), "\n", sep = "")
cat(paste(names(pl), collapse = "|"), "\n", sep = "")
cat(length(pl), "\n", sep = "")
invisible(unlink(f))
