f <- tempfile()
sym <- quote(alpha)
save(sym, file = f, ascii = TRUE)
rm(sym)
cat(paste(load(f, envir = .GlobalEnv), collapse = "|"), "\n", sep = "")
cat(typeof(sym), "\n", sep = "")
cat(deparse(sym), "\n", sep = "")
cat(identical(sym, quote(alpha)), "\n", sep = "")
invisible(unlink(f))
