f <- tempfile()
call <- quote(foo(1L, bar = 2.5, baz = "x"))
save(call, file = f, ascii = TRUE)
rm(call)
cat(paste(load(f, envir = .GlobalEnv), collapse = "|"), "\n", sep = "")
cat(typeof(call), "\n", sep = "")
cat(paste(deparse(call), collapse = " "), "\n", sep = "")
cat(length(call), "\n", sep = "")
cat(paste(names(as.list(call)), collapse = "|"), "\n", sep = "")
cat(paste(vapply(as.list(call), typeof, ""), collapse = "|"), "\n", sep = "")
invisible(unlink(f))
