x <- c(a = 1, b = NA, c = 3)
omit <- na.omit(x)
exclude <- na.exclude(x)
cat(paste(omit, collapse = "|"), "\n", sep = "")
cat(paste(class(attr(omit, "na.action")), collapse = "|"), "\n", sep = "")
cat(paste(attr(omit, "na.action"), collapse = "|"), "\n", sep = "")
cat(paste(names(attr(omit, "na.action")), collapse = "|"), "\n", sep = "")
cat(paste(exclude, collapse = "|"), "\n", sep = "")
cat(paste(class(attr(exclude, "na.action")), collapse = "|"), "\n", sep = "")
cat(paste(attr(exclude, "na.action"), collapse = "|"), "\n", sep = "")
cat(paste(names(attr(exclude, "na.action")), collapse = "|"), "\n", sep = "")
