x <- xtabs(~ c("a", "b", "a"))
y <- ftable(x)
cat(paste(class(y), collapse = "|"), "\n", sep = "")
cat(paste(dim(y), collapse = "|"), "\n", sep = "")
cat(paste(as.vector(y), collapse = "|"), "\n", sep = "")
cat(paste(names(attributes(y)), collapse = "|"), "\n", sep = "")
cat(length(attr(y, "row.vars")), "\n", sep = "")
cat(paste(names(attr(y, "col.vars")), collapse = "|"), "\n", sep = "")
cat(paste(attr(y, "col.vars")[[1]], collapse = "|"), "\n", sep = "")
