z <- aggregate(c(1, 2, 3, 4), list(g = c("a", "a", "b", "b")), min)
w <- aggregate(c(1, 2, 3, 4), list(g = c("a", "a", "b", "b")), max)
cat(paste(names(z), collapse = "|"), "\n", sep = "")
cat(paste(z[[1]], collapse = "|"), "\n", sep = "")
cat(paste(z[[2]], collapse = "|"), "\n", sep = "")
cat(paste(w[[2]], collapse = "|"), "\n", sep = "")
cat(paste(class(z), collapse = "|"), "\n", sep = "")
cat(paste(dim(z), collapse = "|"), "\n", sep = "")
