print(exists("rep.int", mode = "function"))
print(exists("rep_len", mode = "function"))
print(rep.int(c(a = 1L, b = 2L), 3))
print(names(rep.int(c(a = 1L, b = 2L), 3)))
print(rep_len(c("x", "y"), 5))
print(rep_len(1:2, 5))
print(typeof(rep_len(1:2, 5)))
print(rep_len(integer(0), 3))
print(rep_len(character(0), 3))
print(rep_len(raw(0), 3))
