x <- list(a = list(x = 1, y = 2), b = 3)
z <- unlist(x, recursive = FALSE)
cat(typeof(z), "\n", sep = "")
cat(length(z), "\n", sep = "")
cat(paste(names(z), collapse = "|"), "\n", sep = "")
cat(typeof(z[[1]]), "\n", sep = "")
print(z[[1]])
print(z[[2]])

y <- list(a = list(x = list(deep = 1)), b = 2)
zy <- unlist(y, recursive = FALSE)
cat(typeof(zy), "\n", sep = "")
cat(paste(names(zy), collapse = "|"), "\n", sep = "")
cat(typeof(zy[[1]]), "\n", sep = "")
cat(length(zy[[1]]), "\n", sep = "")

w <- unlist(list(a = c(1, 2), b = 3), recursive = FALSE)
cat(typeof(w), "\n", sep = "")
cat(paste(names(w), collapse = "|"), "\n", sep = "")
cat(paste(w, collapse = "|"), "\n", sep = "")
