cat(typeof(cumsum(c(1L, 2L, NA, 4L))), "\n", sep = "")
cat(paste(ifelse(is.na(cumsum(c(1L, 2L, NA, 4L))), "NA", cumsum(c(1L, 2L, NA, 4L))), collapse = "|"), "\n", sep = "")
cat(typeof(cumsum(c(TRUE, FALSE, NA, TRUE))), "\n", sep = "")
cat(paste(ifelse(is.na(cumsum(c(TRUE, FALSE, NA, TRUE))), "NA", cumsum(c(TRUE, FALSE, NA, TRUE))), collapse = "|"), "\n", sep = "")
cat(typeof(cumsum(c(1, 2, NA, 4))), "\n", sep = "")
cat(paste(ifelse(is.na(cumsum(c(1, 2, NA, 4))), "NA", cumsum(c(1, 2, NA, 4))), collapse = "|"), "\n", sep = "")
cat(typeof(cumprod(c(2L, 3L, NA, 4L))), "\n", sep = "")
cat(paste(ifelse(is.na(cumprod(c(2L, 3L, NA, 4L))), "NA", cumprod(c(2L, 3L, NA, 4L))), collapse = "|"), "\n", sep = "")
cat(typeof(cumprod(c(TRUE, FALSE, NA, TRUE))), "\n", sep = "")
cat(paste(ifelse(is.na(cumprod(c(TRUE, FALSE, NA, TRUE))), "NA", cumprod(c(TRUE, FALSE, NA, TRUE))), collapse = "|"), "\n", sep = "")
