cat(typeof(diff(1:5)), "\n", sep = "")
cat(paste(diff(1:5), collapse = "|"), "\n", sep = "")
cat(typeof(diff(c(TRUE, FALSE, TRUE))), "\n", sep = "")
cat(paste(diff(c(TRUE, FALSE, TRUE)), collapse = "|"), "\n", sep = "")
cat(typeof(diff(c(1L, NA, 3L))), "\n", sep = "")
cat(paste(ifelse(is.na(diff(c(1L, NA, 3L))), "NA", diff(c(1L, NA, 3L))), collapse = "|"), "\n", sep = "")
cat(typeof(diff(c(1, 2, 4))), "\n", sep = "")
cat(paste(diff(c(1, 2, 4)), collapse = "|"), "\n", sep = "")
cat(typeof(diff(1:2, lag = 3)), "\n", sep = "")
cat(length(diff(1:2, lag = 3)), "\n", sep = "")
cat(typeof(suppressWarnings(diff(c(-2147483647L, 2147483647L)))), "\n", sep = "")
cat(paste(ifelse(is.na(suppressWarnings(diff(c(-2147483647L, 2147483647L)))), "NA", suppressWarnings(diff(c(-2147483647L, 2147483647L)))), collapse = "|"), "\n", sep = "")
