x <- paste0("a", "\n", "b", "\t", "\\", "\"", rawToChar(as.raw(1)))
r <- serialize(x, NULL, ascii = TRUE)
s <- rawToChar(r)
cat(grepl("\\n", s, fixed = TRUE), "\n", sep = "")
cat(grepl("\\t", s, fixed = TRUE), "\n", sep = "")
cat(grepl("\\\\", s, fixed = TRUE), "\n", sep = "")
cat(grepl("\\\"", s, fixed = TRUE), "\n", sep = "")
cat(grepl("\\001", s, fixed = TRUE), "\n", sep = "")
cat(identical(unserialize(r), x), "\n", sep = "")
