print(pnorm(1, lower.tail = FALSE))
print(pnorm(1, lower.tail = FALSE, log.p = TRUE))
print(pnorm(q = 1, mean = 1, sd = 2))
print(pnorm(1, 1, 2, log.p = TRUE))
print(dbinom(x = 3, size = 10, prob = 0.5))
print(dbinom(3, 10, 0.5, log = TRUE))
print(qnorm(log(0.9), log.p = TRUE))
print(dnorm(1, sd = 2))
print(dnorm(1, log = TRUE))
print(dnorm(x = 1, mean = 2, sd = 3, log = TRUE))
print(pbinom(5, size = 10, prob = 0.5, lower.tail = FALSE))
print(qbinom(p = 0.9, size = 10, prob = 0.5))
print(ppois(2, lambda = 3, lower.tail = FALSE))
print(dpois(x = 2, lambda = 3, log = TRUE))
print(dgamma(2, shape = 3, rate = 2))
print(dgamma(2, shape = 3, scale = 0.5))
print(pgamma(2, shape = 3, rate = 2, lower.tail = FALSE))
print(qgamma(0.9, shape = 3, scale = 0.5))
print(pt(1.5, df = 8, lower.tail = FALSE))
print(dt(1.5, df = 8, log = TRUE))
print(pchisq(3, df = 4, lower.tail = FALSE, log.p = TRUE))
print(dunif(0.5, min = 0, max = 2))
print(punif(q = 0.5, min = 0, max = 2, lower.tail = FALSE))
print(qt(p = 0.95, df = 10))
print(dexp(1, rate = 2, log = TRUE))
print(pweibull(1, shape = 2, scale = 1, lower.tail = FALSE))
print(dnbinom(2, size = 5, prob = 0.3, log = TRUE))
print(pbeta(0.4, shape1 = 2, shape2 = 3, lower.tail = FALSE))
print(qcauchy(0.9, location = 1, scale = 2))
print(pnbinom(3, size = 5, mu = 4, lower.tail = FALSE))
print(pf(2, df1 = 3, df2 = 10, lower.tail = FALSE))
print(qlogis(0.9, location = 1, scale = 2))
print(phyper(2, m = 10, n = 5, k = 4, lower.tail = FALSE))
print(pwilcox(5, m = 4, n = 5, lower.tail = FALSE))
print(psignrank(5, n = 6, lower.tail = FALSE))
print(pnorm(1, low = FALSE))
print(dbinom(3, s = 10, p = 0.5))
