print(TRUE + 1)
print(FALSE + 1)
print(TRUE * 2L)
print(TRUE / 4)
print(-TRUE)
print(as.integer(TRUE))
print(as.numeric(FALSE))
print(as.character(TRUE))
print(sum(c(TRUE, FALSE, TRUE)))
print(mean(rep(TRUE, 4)))
print(TRUE & FALSE)
print(TRUE | NA)
print(!FALSE)
print(if (TRUE) "yes" else "no")
f <- function() TRUE
print(f() + 1)
g <- function(x) x + TRUE
print(g(2))
h <- function() { s <- 0; for (i in 1:3) s <- s + TRUE; s }
print(h())
print(rep(TRUE, 2) + 0:1)
print(c(TRUE, FALSE) * c(3, 4))
print(TRUE == 1)
print(typeof(TRUE))
print(length(TRUE))
print(format(TRUE))
print(paste("v:", TRUE))
