# arithmetic on non-numeric operands and dpq argument validation raise
# the stock error messages
e <- function(expr) tryCatch(expr, error = function(e) cat("ERR:", conditionMessage(e), "\n"))
e(1 + "a")
e(-"a")
e(+"a")
e(-NULL)
e(list(1) + 1)
e("a" %% 2)
e(dnorm("a"))
e(dnorm())
e(dbinom(1, prob = .5))
e(dnbinom(1, 3))
e(dnbinom(1, 3, .2, mu = 5))
e(dnorm(1, mean = NULL))
e(dexp(1, rate = "a"))
e(dgamma(1, 2, rate = 2, scale = 3))
e(abs("a"))
e(abs(NULL))
e(sqrt(list(1)))
e(list(1) == list(1))
e(1i < 2i)
e(factor(c("a", "x")) == factor(c("b", "a")))
cat("arithmetic errors ok\n")
