# Sys.setenv / Sys.getenv in-session propagation
print(Sys.setenv(SCAN_ENV_PROBE = "v1"))
print(Sys.getenv("SCAN_ENV_PROBE"))
print(Sys.setenv(SCAN_ENV_PROBE = "v2", OTHER_PROBE = "xy=1"))
print(Sys.getenv(c("SCAN_ENV_PROBE", "OTHER_PROBE")))
print(Sys.setenv(`A=B` = "x"))
print(Sys.getenv("A=B"))
print(Sys.unsetenv(c("SCAN_ENV_PROBE", "OTHER_PROBE")))
print(Sys.getenv("SCAN_ENV_PROBE", unset = "GONE"))
# scan(text=...)
print(scan(text = "1 2 3"))
print(scan(text = "a b c", what = character()))
print(scan(text = "1,2", sep = ","))
print(scan(text = "1\n2\n3", nlines = 2))
print(scan(text = "", what = integer()))
print(scan(text = "1 2 3", nmax = 2))
print(scan(text = "1 NA 3", na.strings = "NA"))
print(length(scan(text = "x y z", what = character())))
