# complex() constructor parity with stock (base closure + do_complex):
# cartesian real/imaginary form, polar modulus/argument form, closure-style
# positional and partially-tagged argument matching, recycling, NA/Inf
# propagation, and the error paths. Plus format()/str() on symbolic objects
# (call/symbol/expression), which deparse instead of walking the object as a
# vector.
print(complex(1, 2))
print(complex(real = 1, imaginary = 2))
print(complex(length.out = 3))
print(complex(real = 1:3, imaginary = 4:6))
print(complex(1, 1, 1))
print(complex())
print(complex(2, real = 4))
print(complex(0, real = 1, imaginary = 2))
print(complex(3, real = 1:2, imaginary = 5))
print(complex(TRUE))
print(complex(2.5))
print(complex("3"))
z <- complex(1, 2)
print(Re(z))
print(Im(z))
print(complex(modulus = 3, argument = 0.5))
print(complex(2, modulus = 1:2, argument = 0))
print(complex(modulus = 1:3))
print(complex(argument = pi))
print(complex(argument = 1:3, modulus = 2))
print(complex(length.out = 2, argument = c(0, pi)))
print(complex(modulus = c(1, Inf), argument = c(0, 0)))
print(complex(1, 2, 3, 4, 5))
print(complex(2, 1, 2, modulus = 1))
print(complex(modulus = numeric(0), argument = 1))
print(complex(re = 1, im = 2))
print(complex(l = 3))
print(complex(len = 2, real = c(1, NA), imaginary = 3))
print(complex(1, 1, length.out = 2))
msg <- function(e) cat("E:", conditionMessage(e), "\n")
invisible(tryCatch(complex(-1), error = msg))
invisible(tryCatch(complex(NA), error = msg))
invisible(tryCatch(complex(integer(0)), error = msg))
invisible(tryCatch(complex(NA_integer_, modulus = 1), error = msg))
invisible(tryCatch(complex(zzz = 1), error = msg))
invisible(tryCatch(complex(1, 2, 3, 4, 5, 6), error = msg))
print(format(expression(1 + 1)))
print(format(expression(1 + 1, 2 + 2)))
print(format(quote(if (a) b else c)))
d <- str(quote(f(1)))
d <- str(quote(ab))
d <- str(expression(1 + 1))
d <- str(expression(1 + 1, 2 + 2))
d <- str(quote(f(1, 2, 3)))
d <- str(quote({a;b}))
d <- str(quote(`weird name` + 1))
d <- str(quote(x))
print(format(quote(f(1)))[[1]] == "f(1)")
