a <- matrix(c(1,2,3,4),2)
cat(paste(round(solve(a,c(5,6)),10),collapse=","),"\n")
cat(typeof(solve(matrix(c(1L,2L,3L,4L),2),c(5L,6L))),"\n")
cat(inherits(try(solve(diag(c(1,1e-20))),silent=TRUE),"try-error"),"\n")
cat(typeof(mapply(function(x)x,1:3)),"\n")
cat(is.null(names(mapply(function(x)x,c(a=1,b=2),USE.NAMES=FALSE))),"\n")
cat(paste(Filter(function(x) 1,1:3),collapse=","),"\n")
cat(class(Filter(function(x)TRUE,factor(c("a","b")))),"\n")
cat(paste(vapply(1:2,function(x,y)x,integer(1),y=stop("unused")),collapse=","),"\n")
cat(withVisible(withCallingHandlers(1))$visible,"\n")
cat((1:3)[1,drop=NA],"\n")
cat(!is.null(attr(parse(text="x <- 1",keep.source=TRUE),"srcref")),"\n")
cat(paste(as.character(quote(c(b,d))),collapse="|"),"\n")
cat(paste(as.character(quote(f(1+2,x))),collapse="|"),"\n")
cat(identical(as.list(c("Hello ","World","!")),list("Hello ","World","!")),"\n")
cat(identical(as.list(quote(a)),list(quote(a))),"\n")
cat(paste(as.character(quote(`odd name`(`odd arg`))),collapse="|"),"\n")
f <- function(x)x+1
f(2)
cat(typeof(as.list(f)[[2]]),"\n")
cat(identical(as.list(function()1),list(1)),"\n")
z <- matrix(1:4+1i,2,dimnames=list(c("a","b"),c("x","y")))
cat(identical(dimnames(crossprod(z)),list(c("x","y"),c("x","y"))),"\n")
cat(identical(dimnames(tcrossprod(z)),list(c("a","b"),c("a","b"))),"\n")
