x<-seq(0,1,length.out=30); y<-sin(5*x)+cos(31*x)/8; w<-1+x
f<-loess(y~x,weights=w,control=loess.control(statistics='exact'))
cat(paste(round(f$fitted[c(1,15,30)],7),collapse=','),'\n')
p<-predict(f,newdata=c(.2,.5,.8),se=TRUE)
cat(paste(round(p$fit,7),collapse=','),'\n')
cat(paste(round(p$se.fit,7),collapse=','),'\n')
cat(paste(round(c(f$trace.hat,f$one.delta,f$two.delta,f$s),7),collapse=','),'\n')
g<-loess(y~x,weights=w,family='symmetric',control=loess.control(surface='direct'))
cat(paste(round(g$fitted[c(1,15,30)],7),collapse=','),'\n')
cat(paste(round(predict(g,newdata=c(.2,.5,.8),se=TRUE)$se.fit,7),collapse=','),'\n')
h<-loess(y~x,subset=c(30:1,1),model=TRUE)
cat(h$n,nrow(h$model),h$x[1,1],h$x[31,1],'\n')
z<-matrix(1:6,2);z[]<-0;cat(sum(z),'\n')
cat(is.list(sapply(1:2,function(x)new.env())),'\n')
cat(local({predict.example<-function(object,...) 42;predict(structure(1,class='example'))}),'\n')
