x <- c(1, 1e6, 1e-6)
cat(paste(format(x), collapse = "|"), "\n", sep = "")
cat(paste(format(x, scientific = FALSE), collapse = "|"), "\n", sep = "")
cat(paste(format(x, scientific = TRUE), collapse = "|"), "\n", sep = "")
cat(format(1e6), "\n", sep = "")
cat(paste(format(c("a", "bbb")), collapse = "|"), "\n", sep = "")
cat(paste(format(c("a", "bbb"), justify = "right", width = 5), collapse = "|"), "\n", sep = "")
cat(paste(format(c("a", "bbb"), justify = "left", width = 5), collapse = "|"), "\n", sep = "")
cat(paste(format(c("a", "bbb"), justify = "centre", width = 5), collapse = "|"), "\n", sep = "")
cat(paste(format(c("a", "bbb"), justify = "none"), collapse = "|"), "\n", sep = "")
cat(paste(format(c("a", "bbb"), justify = "none", width = 5), collapse = "|"), "\n", sep = "")
