cat(bitwAnd(5L, 3L), "\n", sep = "")
cat(bitwOr(5L, 3L), "\n", sep = "")
cat(bitwXor(5L, 3L), "\n", sep = "")
cat(bitwNot(5L), "\n", sep = "")
cat(bitwShiftL(1L, 3L), "\n", sep = "")
cat(bitwShiftR(16L, 2L), "\n", sep = "")
cat(paste(bitwAnd(c(5L, 7L), 3L), collapse = ","), "\n", sep = "")
cat(is.na(bitwAnd(NA_integer_, 1L)), "\n", sep = "")
cat(bitwAnd(1.5, 2), "\n", sep = "")
cat(typeof(bitwAnd(5L, 3L)), "\n", sep = "")
