cat(paste(encodeString(c("a", "b"), quote = "\""), collapse = "|"), "\n", sep = "")
cat(paste(encodeString(c("a", "bb"), width = 5, justify = "right"), collapse = "|"), "\n", sep = "")
cat(encodeString("a\\b\n", quote = "\""), "\n", sep = "")
cat(encodeString(NA_character_), "\n", sep = "")
cat(paste(encodeString(c("a", "b"), quote = "'"), collapse = "|"), "\n", sep = "")
cat(paste(encodeString(c("a", "bb"), width = 4, justify = "left"), collapse = "|"), "\n", sep = "")
cat(paste(encodeString(c("a", "bb"), width = 4, justify = "centre"), collapse = "|"), "\n", sep = "")
cat(paste(encodeString(c("a", "bb"), justify = "none"), collapse = "|"), "\n", sep = "")
cat(identical(as.name("x"), as.symbol("x")), "\n", sep = "")
