g <- expand.grid(1:2, 3:4)
cat(paste(g$Var1, collapse = ","), "\n", sep = "")
cat(paste(g$Var2, collapse = ","), "\n", sep = "")
cat(paste(class(g), collapse = ","), "\n", sep = "")
cat(nrow(g), "\n", sep = "")
cat(paste(attr(g, "out.attrs")$dim, collapse = ","), "\n", sep = "")
g2 <- expand.grid(a = 1:2, b = c("x", "y"))
cat(paste(g2$a, collapse = ","), "\n", sep = "")
cat(paste(as.character(g2$b), collapse = ","), "\n", sep = "")
cat(paste(levels(g2$b), collapse = ","), "\n", sep = "")
cat(is.factor(g2$b), "\n", sep = "")
