ct <- chisq.test(c(10, 10, 10))
cat(as.numeric(ct$statistic), "\n", sep = "")
cat(as.numeric(ct$parameter), "\n", sep = "")
cat(ct$p.value, "\n", sep = "")
cat(ct$method, "\n", sep = "")
ct2 <- chisq.test(c(10, 20, 30))
cat(round(as.numeric(ct2$statistic), 6), "\n", sep = "")
cat(round(ct2$p.value, 8), "\n", sep = "")
cat(class(ct), "\n", sep = "")
