x <- matrix(c(10, 2, 3, 10), 2)
mt <- mcnemar.test(x)
cat(as.numeric(mt$statistic), "\n", sep = "")
cat(as.numeric(mt$parameter), "\n", sep = "")
cat(mt$p.value, "\n", sep = "")
cat(mt$method, "\n", sep = "")
mt2 <- mcnemar.test(x, correct = FALSE)
cat(round(as.numeric(mt2$statistic), 6), "\n", sep = "")
cat(round(mt2$p.value, 6), "\n", sep = "")
cat(class(mt), "\n", sep = "")
