pw <- power.anova.test(groups = 3, n = 5, between.var = 1, within.var = 1)
cat(pw$groups, "\n", sep = "")
cat(pw$n, "\n", sep = "")
cat(pw$between.var, "\n", sep = "")
cat(pw$within.var, "\n", sep = "")
cat(pw$sig.level, "\n", sep = "")
cat(round(pw$power, 6), "\n", sep = "")
cat(pw$method, "\n", sep = "")
cat(class(pw), "\n", sep = "")
