x <- c(1, 2, 3, 4, 5, 6, 7, 8, 10)
g <- factor(rep(1:3, each = 3))
eq <- oneway.test(x ~ g, var.equal = TRUE)
uneq <- oneway.test(x ~ g, var.equal = FALSE)
cat(round(as.numeric(eq$statistic), 4), "\n", sep = "")
cat(paste(round(as.numeric(eq$parameter), 4), collapse = ","), "\n", sep = "")
cat(round(eq$p.value, 6), "\n", sep = "")
cat(eq$method, "\n", sep = "")
cat(round(as.numeric(uneq$statistic), 4), "\n", sep = "")
cat(paste(round(as.numeric(uneq$parameter), 4), collapse = ","), "\n", sep = "")
cat(round(uneq$p.value, 6), "\n", sep = "")
cat(uneq$method, "\n", sep = "")
cat(class(eq), "\n", sep = "")
