y <- c(1, 2, 2, 4, 5, 6)
x1 <- c(1, 2, 3, 4, 5, 6)
x2 <- c(1, 1, 2, 2, 3, 3)
fit <- lm(y ~ x1 + x2)
cat(paste(round(as.numeric(coef(fit)), 4), collapse = ","), "\n", sep = "")
cat(paste(round(as.numeric(fitted(fit)), 4), collapse = ","), "\n", sep = "")
cat(fit$rank, "\n", sep = "")
cat(fit$df.residual, "\n", sep = "")
cat(paste(names(coef(fit)), collapse = ","), "\n", sep = "")
