set.seed(1)
cat(paste(round(rsmirnov(8, c(5, 5)), 4), collapse = ","), "\n", sep = "")
set.seed(1)
cat(paste(round(rsmirnov(8, c(5, 5), alternative = "two.sided"), 4), collapse = ","), "\n", sep = "")
set.seed(1)
cat(paste(round(rsmirnov(8, c(5, 5), alternative = "less"), 4), collapse = ","), "\n", sep = "")
set.seed(1)
cat(paste(round(rsmirnov(8, c(5, 7), alternative = "less"), 4), collapse = ","), "\n", sep = "")
set.seed(1)
cat(paste(round(rsmirnov(8, c(5, 7), alternative = "greater"), 4), collapse = ","), "\n", sep = "")
