# Generated by pinned GNU R bac583951b728e97b9786804d3b4081f0fe18df5.
message <- call <- NULL
bytes <- withCallingHandlers(charToRaw(c("first", "ignored")), warning=function(w) {
    message <<- conditionMessage(w)
    call <<- paste(deparse(conditionCall(w)), collapse=" ")
    invokeRestart("muffleWarning")
})
cat("message=", gsub("\n", "|", message, fixed=TRUE), "\n", sep="")
cat("call=", call, "\n", sep="")
cat("bytes=", paste(bytes, collapse="|"), "\n", sep="")
options(warn=2)
error <- tryCatch(charToRaw(c("first", "ignored")), error=identity)
cat("error=", gsub("\n", "|", conditionMessage(error), fixed=TRUE), "\n", sep="")
cat("error_call=", paste(deparse(conditionCall(error)), collapse=" "), "\n", sep="")
options(warn=0)
cat("recovery=", paste(charToRaw("ok"), collapse="|"), "\n", sep="")
