#!/usr/bin/env python3
"""Generate inventory counts from the checked-in compatibility ledgers.

These are test and disposition counts, not implementation percentages.
Use --check in CI to detect stale documentation.
"""
import argparse
import collections
import json
from pathlib import Path
import tomllib

root = Path(__file__).resolve().parent.parent
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
fixtures = {folder: len(list((root / 'tests/conformance' / folder).glob('*.R')))
            for folder in ('cases', 'error_cases')}
rows = [line.split('\t') for line in (root / 'tests/upstream-r/dispositions.tsv').read_text().splitlines()
        if line and not line.startswith('#')]
upstream = collections.Counter(row[1] for row in rows)
packages = tomllib.loads((root / 'tests/real-packages/manifest.toml').read_text())['package']
package_status = collections.Counter(p['status'] for p in packages)
checkpoint_path = root / 'docs/ci-checkpoints/37259644379.json'
checkpoint = json.loads(checkpoint_path.read_text())
observed = checkpoint['sets']
latest_path = root / 'docs/ci-checkpoints/package-showcase-6823f00e.json'
latest = json.loads(latest_path.read_text())
current_conformance = latest['conformance']
current_upstream = latest['complete_upstream']
current_checks = {check['check']: check for check in latest['checks']}
showcase = current_checks['Complete Chromium showcase']
embedding = current_checks['Complete native public embedding suite']
public_path = root / 'docs/ci-checkpoints/public-workflows-d339e355.json'
public = json.loads(public_path.read_text())
public_checks = {check['id']: check for check in public['checks']}
integration_path = root / 'docs/ci-checkpoints/integration-stabilization-e3e26dea.json'
integration = json.loads(integration_path.read_text())
integration_checks = {check['id']: check for check in integration['checks']}
integration_conformance = integration['complete_conformance']
integration_linux = integration['linux_showcase_525']
integration_upstream = integration['complete_upstream']
integration_local = integration['wasm_process_identity']
report = f'''# Compatibility evidence inventory

Generated by `python3 scripts/capability_report.py` from checked-in fixtures and
manifests. Counts describe declared evidence, not the percentage of R implemented
or a claim that tests passed on a particular commit.

| Inventory | Count |
| --- | ---: |
| Curated ordinary fixtures | {fixtures['cases']} |
| Curated error fixtures | {fixtures['error_cases']} |
| Total curated fixtures | {sum(fixtures.values())} |
| Whole upstream files tracked | {len(rows)} |
| Upstream files declared expected-pass | {upstream['pass']} |
| Upstream files marked xfail | {upstream['xfail']} |
| Upstream files marked skip | {upstream['skip']} |
| Real packages with selected probes | {len(packages)} |
| Package probe sets declared expected-pass | {package_status['pass']} |
| Package probe sets marked partial | {package_status['partial']} |
| Package probe sets marked blocked | {package_status['blocked']} |

Whole-file dispositions are in `tests/upstream-r/dispositions.tsv`; package
versions, hashes, probes and blockers are in `tests/real-packages/manifest.toml`.
Passing selected package probes does not establish full package compatibility.

The inspected [execution checkpoint]({checkpoint['run_url']}) used commit
`{checkpoint['source_commit']}`. Its downloaded artifact summaries are captured in
[`docs/ci-checkpoints/37259644379.json`](ci-checkpoints/37259644379.json), with their
SHA-256 hashes. These observed results supersede historical passing declarations
for that snapshot; they do not verify later source changes.

| Executed set | Pass | Fail | Other |
| --- | ---: | ---: | --- |
| Exact-oracle conformance | {observed['conformance']['status_counts']['pass']} | {observed['conformance']['status_counts']['fail']} | All {observed['conformance']['inventory_total']} accounted for; {observed['conformance']['timed_out']} timeouts |
| Whole upstream drivers | {observed['upstream']['by_kind']['whole']['pass']} | {observed['upstream']['by_kind']['whole']['fail']} | {observed['upstream']['by_kind']['whole']['skip']} skipped; 1 without a completed result |
| Curated upstream slices | {observed['upstream']['by_kind']['curated']['pass']} | {observed['upstream']['by_kind']['curated']['fail']} | All 15 accounted for |
| Showcase Chromium | {observed['showcase']['stats']['expected']} | {observed['showcase']['stats']['unexpected']} | {observed['showcase']['stats']['skipped']} skipped; {observed['showcase']['stats']['flaky']} flaky |

The whole-driver join is incomplete because `utf8.R` has no completed result.
`reg-plot-latin1.R` failed on the GNU side, so that row does not establish a Rust
runtime defect. Other failing rows preserve their recorded classification in the
checkpoint. The runner's release profile alone does not establish its feature,
device, package-policy or numerical-backend configuration.

Later executed evidence is recorded separately in the
[package/showcase receipt](ci-checkpoints/package-showcase-6823f00e.json).

| Executed set | Commit | Pass | Fail | Other |
| --- | --- | ---: | ---: | --- |
| Complete exact-oracle conformance | `{current_conformance['source_commit'][:8]}` | {current_conformance['status_counts']['pass']} | {current_conformance['status_counts']['fail']} | All {current_conformance['inventory_total']} accounted for; {current_conformance['timed_out']} timeouts |
| Complete whole upstream drivers | `{current_upstream['source_commit'][:8]}` | {current_upstream['by_kind']['whole']['pass']} | {current_upstream['by_kind']['whole']['fail']} | {current_upstream['by_kind']['whole']['skip']} skipped; all 70 accounted for |
| Complete curated upstream slices | `{current_upstream['source_commit'][:8]}` | {current_upstream['by_kind']['curated']['pass']} | {current_upstream['by_kind']['curated']['fail']} | All 15 accounted for |
| Complete native embedding suite | `{embedding['source_commit'][:8]}` | {embedding['passed']} | {embedding['failed']} | Actual default and portable public constructors |
| Complete Chromium showcase | `{showcase['source_commit'][:8]}` | {showcase['passed']} | {showcase['failed']} | Original 59 plus reset/reimport regression; {showcase['skipped']} skipped; {showcase['flaky']} flaky |

The browser run uses the production Wasm bytes identified by the receipt.
The unchanged sunflower gallery and editor/download flows also pass twice each
on the actual release build output. The original 15-second evaluation and
25 MiB package budgets remain in effect. The complete upstream CI union now
accounts for all 85 workloads. UTF-8 completes in the intended 1800-second
profile with a strict output difference (Rust execution takes 1335.122 seconds).
Linux GNU Latin-1 setup succeeds; its strict output difference remains a
separate failure. Earlier selected 180-second diagnostics retain their own
timeout classifications and do not replace the complete CI results. The receipt
retains explicit feature, device, package and numerical profiles and every
conformance and upstream outcome. These reports identify their actual source
commits; later focused repairs are not a new complete union.

A newer [public-workflow receipt](ci-checkpoints/public-workflows-d339e355.json)
joins selected namespace/binding inventory keys to their public wrappers,
implementation paths, tested options, execution profiles and source commits.
Runtime source is `{public['runtime_source_commit'][:8]}`; the command-history
caret repair is `{public['website_source_commit'][:8]}`. The fresh native
embedding suite passes {public_checks['native_packages']['passed']}/39, portable methods pass
{public_checks['portable_methods']['passed']}/8, and Chromium passes {public_checks['showcase']['passed']}/60
with zero skipped or flaky cases. Both unchanged sunflower flows pass twice.
Strict Miri covers shared-frame invalidation, allocation-failure fallback and GC.
The unchanged whole `structure.R` passes under both debug and the intended
graphics/native/faer release profile. `eval-etc.R` now completes successfully in
both profiles, but still fails strict output comparison. These selected results
do not replace the complete conformance/upstream unions above.

The later [integration stabilization receipt](ci-checkpoints/integration-stabilization-e3e26dea.json)
records actual public workflow repairs and preserves their separate source commits.

| Executed set | Commit | Pass | Fail | Other |
| --- | --- | ---: | ---: | --- |
| Complete exact-oracle conformance | `{integration_conformance['source_commit'][:8]}` | {integration_conformance['status_counts']['pass']} | {integration_conformance['status_counts']['fail']} | All {integration_conformance['inventory_total']} accounted for; {integration_conformance['timed_out']} timeouts |
| Complete whole upstream drivers | `{integration_upstream['source_commit'][:8]}` | {integration_upstream['by_kind']['whole']['pass']} | {integration_upstream['by_kind']['whole']['fail']} | {integration_upstream['by_kind']['whole']['skip']} skipped; all 70 accounted for |
| Complete curated upstream slices | `{integration_upstream['source_commit'][:8]}` | {integration_upstream['by_kind']['curated']['pass']} | {integration_upstream['by_kind']['curated']['fail']} | All 15 accounted for |
| Local complete Chromium showcase | `{integration_local['source_commit'][:8]}` | {integration_local['showcase']['stats']['expected']} | {integration_local['showcase']['stats']['unexpected']} | Original 59 plus reset regression; zero skipped or flaky |
| Linux complete Chromium showcase | `{integration_linux['source_commit'][:8]}` | {integration_linux['stats']['expected']} | {integration_linux['stats']['unexpected']} | All 60 accounted for; zero skipped or flaky |
| Public native package/data workflows | `{integration_checks['native_packages_and_data']['source_commit'][:8]}` | {integration_checks['native_packages_and_data']['passed']} | {integration_checks['native_packages_and_data']['failed']} | Includes all 39 embedding tests and both actual constructor policies |
| Original Wasm dataset contracts | `{integration_checks['wasm_datasets']['source_commit'][:8]}` | {integration_checks['wasm_datasets']['passed']} | {integration_checks['wasm_datasets']['failed']} | 108 original objects; 91 topics; 592931 exact serialized graph bytes |
| Unchanged whole `eval-etc.R` | `c4de20b5` | 1 | 0 | Strict GNU comparison; graphics/native/faer release |
| Unchanged whole `structure.R` | `c4de20b5` | 1 | 0 | Strict GNU comparison; graphics/native/faer release |
| Unchanged whole `reg-S4.R` | `4b48f0b0` | 1 | 0 | Strict GNU comparison; graphics/native/faer release |

The complete conformance reduction is eight failures relative to the reviewed
checkpoint. Later selected case 538 passes after shared `try` rendering repairs;
case 540 still differs in warning call attribution. Selected checks do not alter
the complete union totals. The original `utils::data` closure now reaches its
portable package-shaped path and original serialized assets through the real
file/namespace routes. No helpers are injected into the global environment.
Public `require` emits real startup conditions and respects quiet and repeated
attachment; public `try` preserves nested and explicit condition calls. At
`f16592b7`, calling error handlers receive real conditions before unwind: the
original pinned GNU `.handleSimpleError` is installed in canonical base and called
with the handler, message and quoted originating call. Both constructor policies,
call-free and custom conditions, help-call attribution and callback collection
pass, together with 21 existing owned condition/restart controls and the same
public contract in two fresh production Wasm sessions.
The complete upstream union accounts for all 85 workloads under the explicit
graphics/native/faer release profile. UTF-8 completes (Rust 1024.246 seconds)
with a strict output difference. GNU Latin-1 setup succeeds; Rust explicitly
rejects the unfinished native `C_mtext` operation. Earlier incomplete or
shorter diagnostic reports retain their classifications.

Local methods profiling improves from 14.7/16.2 seconds to 10.528 seconds after
checked package-byte initialization. A later controlled comparison measures
9.920 seconds before amortized collection headroom and 6.058 seconds after it,
with cold initialization measured separately. The original 15-second evaluation,
64 MiB heap and 500000-node budgets remain unchanged. Immutable Linux `9b500c00`
passes all 60 showcase cases with zero skips or flaky results, including all
previous methods timeouts and both sunflower flows. Existing forced-GC and
64 MiB retention checks also pass. The earlier Linux failures remain in the receipt.

GNU instruction storage reduces the debug dispatcher frame from 27584 to 4416
bytes; existing private VM controls and strict Miri pass. Local production
`196e62eb` passes all 60 showcase cases. This source still reproduces the native
stack abort through the explicit portable constructor, despite passing native-host
checks. The later `52586600` checked-metadata storage repair passes all four grid
workflows under both policies at the unchanged stack budget, plus all 57 public
controls, 25 private VM controls, strict Miri, formatting and Clippy. Its immutable
Linux checkpoint also passes the original grid workflows under both policies and
all 60 browser tests. The Linux workspace advances to 38/39 embedding tests,
where the device-lifecycle workflow still depends on a missing host R
configuration file; this is tracked separately. The older exhaustive workspace run
is incomplete; it is not current-HEAD passing evidence.
The original GNU `grDevices` package image at `0105a3ff` provides canonical
namespace initialization and 137 captured exports under the explicit empty
portable library policy. The unchanged device-lifecycle workflow passes through
both real constructors after repairing the shared builtin `par` query path.
All 39 native embedding tests pass locally, along with seven namespace/window
controls and the original grid workflows. Two fresh production Wasm sessions
pass the same namespace/device workflow and encode a real PNG; all 205 original
dataset checks and the complete 60-case browser suite pass. A focused immutable
Linux package checkpoint completes all 46 public package checks without host R
discovery. The separate Linux browser workbench fails at serialized recording
because `Sys.getpid()` calls an unsupported host API on Wasm; its showcase
suite is not reached. The earlier local 60-case result remains separately
sourced. A broader forced-GC recording invocation was manually cancelled and
is not counted as complete. Captured exports do not imply that every export
has a completed native implementation.

The later `96742f34` repair gives native `try`/`tryCatch` an owned evaluation
context and correctly returns no inferred caller for a lone top-level builtin.
The original top-level stop cases and existing nested, explicit and callback
condition workflows pass through both public constructors. At `7a4f7314`,
`Sys.getpid()` uses a stable virtual process identity on browser Wasm, avoiding
the host API panic in the original GNU `recordPlot()` wrapper. Two fresh
production sessions pass the original six workbench plots, serialized replay,
all condition fixtures and all 205 dataset checks; the unchanged browser
workbench test and full 60-case showcase also pass locally.
The `c608eefa` CI repair keeps strict producer reports outside restored Cargo
caches. Its immutable checkpoint is pending; the earlier upstream jobs that
failed receipt admission do not supply current driver results.

The explicit native error-call repair at `1d06a03c` preserves the supplied
`letters@foo` call while retaining GNU inferred `stop` calls and callback
replacement attribution. The unchanged complete `method-dispatch.R` passes
strict comparison under graphics/native/faer release.

The table printing repair at `06773bdc` uses the original GNU closure and shared
output paths. Both public constructor policies match independently captured GNU
output for formatting options, dimensions, missing names and capture chronology.
The unchanged original conformance case 1091 and curated slice 008 also pass
strict comparison in the explicit release profile. These selected results do
not change the complete union counts above.

The receipt joins each selected inventory key to actual wrappers, implementation
paths, options, edge cases, profiles, source commits and raw-report hashes.

Run strict three-way parity with the pinned oracle, workspace tests, Miri and
platform checks for executable evidence. See `docs/safe-api-audit.md` for the
owned public API and bounded unsafe implementation, and
`docs/web-architecture.md` for the Rust browser runtime and its limits.
'''
output = root / 'docs/capability-evidence.md'
if args.check:
    if not output.exists() or output.read_text() != report:
        raise SystemExit('Capability inventory is stale; run python3 scripts/capability_report.py')
else:
    output.write_text(report)
