#!/usr/bin/env python3
"""Generate inventory counts from the checked-in compatibility ledgers.

These are test and disposition counts, not implementation percentages.
Use --check in CI to detect stale documentation.
"""
import argparse
import collections
import json
from pathlib import Path
import tomllib

root = Path(__file__).resolve().parent.parent
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
fixtures = {folder: len(list((root / 'tests/conformance' / folder).glob('*.R')))
            for folder in ('cases', 'error_cases')}
rows = [line.split('\t') for line in (root / 'tests/upstream-r/dispositions.tsv').read_text().splitlines()
        if line and not line.startswith('#')]
upstream = collections.Counter(row[1] for row in rows)
packages = tomllib.loads((root / 'tests/real-packages/manifest.toml').read_text())['package']
package_status = collections.Counter(p['status'] for p in packages)
checkpoint_path = root / 'docs/ci-checkpoints/37259644379.json'
checkpoint = json.loads(checkpoint_path.read_text())
observed = checkpoint['sets']
latest_path = root / 'docs/ci-checkpoints/package-showcase-6823f00e.json'
latest = json.loads(latest_path.read_text())
current_conformance = latest['conformance']
current_upstream = latest['complete_upstream']
current_checks = {check['check']: check for check in latest['checks']}
showcase = current_checks['Complete Chromium showcase']
embedding = current_checks['Complete native public embedding suite']
report = f'''# Compatibility evidence inventory

Generated by `python3 scripts/capability_report.py` from checked-in fixtures and
manifests. Counts describe declared evidence, not the percentage of R implemented
or a claim that tests passed on a particular commit.

| Inventory | Count |
| --- | ---: |
| Curated ordinary fixtures | {fixtures['cases']} |
| Curated error fixtures | {fixtures['error_cases']} |
| Total curated fixtures | {sum(fixtures.values())} |
| Whole upstream files tracked | {len(rows)} |
| Upstream files declared expected-pass | {upstream['pass']} |
| Upstream files marked xfail | {upstream['xfail']} |
| Upstream files marked skip | {upstream['skip']} |
| Real packages with selected probes | {len(packages)} |
| Package probe sets declared expected-pass | {package_status['pass']} |
| Package probe sets marked partial | {package_status['partial']} |
| Package probe sets marked blocked | {package_status['blocked']} |

Whole-file dispositions are in `tests/upstream-r/dispositions.tsv`; package
versions, hashes, probes and blockers are in `tests/real-packages/manifest.toml`.
Passing selected package probes does not establish full package compatibility.

The inspected [execution checkpoint]({checkpoint['run_url']}) used commit
`{checkpoint['source_commit']}`. Its downloaded artifact summaries are captured in
[`docs/ci-checkpoints/37259644379.json`](ci-checkpoints/37259644379.json), with their
SHA-256 hashes. These observed results supersede historical passing declarations
for that snapshot; they do not verify later source changes.

| Executed set | Pass | Fail | Other |
| --- | ---: | ---: | --- |
| Exact-oracle conformance | {observed['conformance']['status_counts']['pass']} | {observed['conformance']['status_counts']['fail']} | All {observed['conformance']['inventory_total']} accounted for; {observed['conformance']['timed_out']} timeouts |
| Whole upstream drivers | {observed['upstream']['by_kind']['whole']['pass']} | {observed['upstream']['by_kind']['whole']['fail']} | {observed['upstream']['by_kind']['whole']['skip']} skipped; 1 without a completed result |
| Curated upstream slices | {observed['upstream']['by_kind']['curated']['pass']} | {observed['upstream']['by_kind']['curated']['fail']} | All 15 accounted for |
| Showcase Chromium | {observed['showcase']['stats']['expected']} | {observed['showcase']['stats']['unexpected']} | {observed['showcase']['stats']['skipped']} skipped; {observed['showcase']['stats']['flaky']} flaky |

The whole-driver join is incomplete because `utf8.R` has no completed result.
`reg-plot-latin1.R` failed on the GNU side, so that row does not establish a Rust
runtime defect. Other failing rows preserve their recorded classification in the
checkpoint. The runner's release profile alone does not establish its feature,
device, package-policy or numerical-backend configuration.

Later executed evidence is recorded separately in the
[package/showcase receipt](ci-checkpoints/package-showcase-6823f00e.json).

| Executed set | Commit | Pass | Fail | Other |
| --- | --- | ---: | ---: | --- |
| Complete exact-oracle conformance | `{current_conformance['source_commit'][:8]}` | {current_conformance['status_counts']['pass']} | {current_conformance['status_counts']['fail']} | All {current_conformance['inventory_total']} accounted for; {current_conformance['timed_out']} timeouts |
| Complete whole upstream drivers | `{current_upstream['source_commit'][:8]}` | {current_upstream['by_kind']['whole']['pass']} | {current_upstream['by_kind']['whole']['fail']} | {current_upstream['by_kind']['whole']['skip']} skipped; all 70 accounted for |
| Complete curated upstream slices | `{current_upstream['source_commit'][:8]}` | {current_upstream['by_kind']['curated']['pass']} | {current_upstream['by_kind']['curated']['fail']} | All 15 accounted for |
| Complete native embedding suite | `{embedding['source_commit'][:8]}` | {embedding['passed']} | {embedding['failed']} | Actual default and portable public constructors |
| Complete Chromium showcase | `{showcase['source_commit'][:8]}` | {showcase['passed']} | {showcase['failed']} | Original 59 plus reset/reimport regression; {showcase['skipped']} skipped; {showcase['flaky']} flaky |

The browser run uses the production Wasm bytes identified by the receipt.
The unchanged sunflower gallery and editor/download flows also pass twice each
on the actual release build output. The original 15-second evaluation and
25 MiB package budgets remain in effect. The complete upstream CI union now
accounts for all 85 workloads. UTF-8 completes in the intended 1800-second
profile with a strict output difference (Rust execution takes 1335.122 seconds).
Linux GNU Latin-1 setup succeeds; its strict output difference remains a
separate failure. Earlier selected 180-second diagnostics retain their own
timeout classifications and do not replace the complete CI results. The receipt
retains explicit feature, device, package and numerical profiles and every
conformance and upstream outcome. These reports identify their actual source
commits; later focused repairs are not a new complete union.

Run strict three-way parity with the pinned oracle, workspace tests, Miri and
platform checks for executable evidence. See `docs/safe-api-audit.md` for the
owned public API and bounded unsafe implementation, and
`docs/web-architecture.md` for the Rust browser runtime and its limits.
'''
output = root / 'docs/capability-evidence.md'
if args.check:
    if not output.exists() or output.read_text() != report:
        raise SystemExit('Capability inventory is stale; run python3 scripts/capability_report.py')
else:
    output.write_text(report)
