#!/usr/bin/env python3
"""Generate inventory counts from the checked-in compatibility ledgers.

These are test and disposition counts, not implementation percentages.
Use --check in CI to detect stale documentation.
"""
import argparse
import collections
import json
from pathlib import Path
import tomllib

root = Path(__file__).resolve().parent.parent
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
fixtures = {folder: len(list((root / 'tests/conformance' / folder).glob('*.R')))
            for folder in ('cases', 'error_cases')}
rows = [line.split('\t') for line in (root / 'tests/upstream-r/dispositions.tsv').read_text().splitlines()
        if line and not line.startswith('#')]
upstream = collections.Counter(row[1] for row in rows)
packages = tomllib.loads((root / 'tests/real-packages/manifest.toml').read_text())['package']
package_status = collections.Counter(p['status'] for p in packages)
checkpoint_path = root / 'docs/ci-checkpoints/37259644379.json'
checkpoint = json.loads(checkpoint_path.read_text())
observed = checkpoint['sets']
latest_path = root / 'docs/ci-checkpoints/package-showcase-6823f00e.json'
latest = json.loads(latest_path.read_text())
current_conformance = latest['conformance']
current_upstream = latest['complete_upstream']
current_checks = {check['check']: check for check in latest['checks']}
showcase = current_checks['Complete Chromium showcase']
embedding = current_checks['Complete native public embedding suite']
public_path = root / 'docs/ci-checkpoints/public-workflows-d339e355.json'
public = json.loads(public_path.read_text())
public_checks = {check['id']: check for check in public['checks']}
integration_path = root / 'docs/ci-checkpoints/integration-stabilization-e3e26dea.json'
integration = json.loads(integration_path.read_text())
integration_checks = {check['id']: check for check in integration['checks']}
integration_conformance = integration['complete_conformance']
integration_linux = integration['linux_showcase_04c']
integration_upstream = integration['complete_upstream']
integration_local = integration['batch_last_value']
view_path = root / 'docs/ci-checkpoints/native-view-methods-6ccae790.json'
view = json.loads(view_path.read_text())
view_checks = view['validation']
complete = json.loads((root / 'docs/ci-checkpoints/complete-inventory-91babc00.json').read_text())
linux_profile = json.loads((root / 'docs/ci-checkpoints/linux-workflow-profile-91babc00.json').read_text())
correlation = json.loads((root / 'docs/ci-checkpoints/correlation-b9d1bef7.json').read_text())
report = f'''# Compatibility evidence inventory

Generated by `python3 scripts/capability_report.py` from checked-in fixtures and
manifests. Counts describe declared evidence, not the percentage of R implemented
or a claim that tests passed on a particular commit.

| Inventory | Count |
| --- | ---: |
| Curated ordinary fixtures | {fixtures['cases']} |
| Curated error fixtures | {fixtures['error_cases']} |
| Total curated fixtures | {sum(fixtures.values())} |
| Whole upstream files tracked | {len(rows)} |
| Upstream files declared expected-pass | {upstream['pass']} |
| Upstream files marked xfail | {upstream['xfail']} |
| Upstream files marked skip | {upstream['skip']} |
| Real packages with selected probes | {len(packages)} |
| Package probe sets declared expected-pass | {package_status['pass']} |
| Package probe sets marked partial | {package_status['partial']} |
| Package probe sets marked blocked | {package_status['blocked']} |

Whole-file dispositions are in `tests/upstream-r/dispositions.tsv`; package
versions, hashes, probes and blockers are in `tests/real-packages/manifest.toml`.
Passing selected package probes does not establish full package compatibility.

The inspected [execution checkpoint]({checkpoint['run_url']}) used commit
`{checkpoint['source_commit']}`. Its downloaded artifact summaries are captured in
[`docs/ci-checkpoints/37259644379.json`](ci-checkpoints/37259644379.json), with their
SHA-256 hashes. These observed results supersede historical passing declarations
for that snapshot; they do not verify later source changes.

| Executed set | Pass | Fail | Other |
| --- | ---: | ---: | --- |
| Exact-oracle conformance | {observed['conformance']['status_counts']['pass']} | {observed['conformance']['status_counts']['fail']} | All {observed['conformance']['inventory_total']} accounted for; {observed['conformance']['timed_out']} timeouts |
| Whole upstream drivers | {observed['upstream']['by_kind']['whole']['pass']} | {observed['upstream']['by_kind']['whole']['fail']} | {observed['upstream']['by_kind']['whole']['skip']} skipped; 1 without a completed result |
| Curated upstream slices | {observed['upstream']['by_kind']['curated']['pass']} | {observed['upstream']['by_kind']['curated']['fail']} | All 15 accounted for |
| Showcase Chromium | {observed['showcase']['stats']['expected']} | {observed['showcase']['stats']['unexpected']} | {observed['showcase']['stats']['skipped']} skipped; {observed['showcase']['stats']['flaky']} flaky |

The whole-driver join is incomplete because `utf8.R` has no completed result.
`reg-plot-latin1.R` failed on the GNU side, so that row does not establish a Rust
runtime defect. Other failing rows preserve their recorded classification in the
checkpoint. The runner's release profile alone does not establish its feature,
device, package-policy or numerical-backend configuration.

Later executed evidence is recorded separately in the
[package/showcase receipt](ci-checkpoints/package-showcase-6823f00e.json).

| Executed set | Commit | Pass | Fail | Other |
| --- | --- | ---: | ---: | --- |
| Complete exact-oracle conformance | `{current_conformance['source_commit'][:8]}` | {current_conformance['status_counts']['pass']} | {current_conformance['status_counts']['fail']} | All {current_conformance['inventory_total']} accounted for; {current_conformance['timed_out']} timeouts |
| Complete whole upstream drivers | `{current_upstream['source_commit'][:8]}` | {current_upstream['by_kind']['whole']['pass']} | {current_upstream['by_kind']['whole']['fail']} | {current_upstream['by_kind']['whole']['skip']} skipped; all 70 accounted for |
| Complete curated upstream slices | `{current_upstream['source_commit'][:8]}` | {current_upstream['by_kind']['curated']['pass']} | {current_upstream['by_kind']['curated']['fail']} | All 15 accounted for |
| Complete native embedding suite | `{embedding['source_commit'][:8]}` | {embedding['passed']} | {embedding['failed']} | Actual default and portable public constructors |
| Complete Chromium showcase | `{showcase['source_commit'][:8]}` | {showcase['passed']} | {showcase['failed']} | Original 59 plus reset/reimport regression; {showcase['skipped']} skipped; {showcase['flaky']} flaky |

The browser run uses the production Wasm bytes identified by the receipt.
The unchanged sunflower gallery and editor/download flows also pass twice each
on the actual release build output. The original 15-second evaluation and
25 MiB package budgets remain in effect. The complete upstream CI union now
accounts for all 85 workloads. UTF-8 completes in the intended 1800-second
profile with a strict output difference (Rust execution takes 1335.122 seconds).
Linux GNU Latin-1 setup succeeds; its strict output difference remains a
separate failure. Earlier selected 180-second diagnostics retain their own
timeout classifications and do not replace the complete CI results. The receipt
retains explicit feature, device, package and numerical profiles and every
conformance and upstream outcome. These reports identify their actual source
commits; later focused repairs are not a new complete union.

A newer [public-workflow receipt](ci-checkpoints/public-workflows-d339e355.json)
joins selected namespace/binding inventory keys to their public wrappers,
implementation paths, tested options, execution profiles and source commits.
Runtime source is `{public['runtime_source_commit'][:8]}`; the command-history
caret repair is `{public['website_source_commit'][:8]}`. The fresh native
embedding suite passes {public_checks['native_packages']['passed']}/39, portable methods pass
{public_checks['portable_methods']['passed']}/8, and Chromium passes {public_checks['showcase']['passed']}/60
with zero skipped or flaky cases. Both unchanged sunflower flows pass twice.
Strict Miri covers shared-frame invalidation, allocation-failure fallback and GC.
The unchanged whole `structure.R` passes under both debug and the intended
graphics/native/faer release profile. `eval-etc.R` now completes successfully in
both profiles, but still fails strict output comparison. These selected results
do not replace the complete conformance/upstream unions above.

The later [integration stabilization receipt](ci-checkpoints/integration-stabilization-e3e26dea.json)
records actual public workflow repairs and preserves their separate source commits.

| Executed set | Commit | Pass | Fail | Other |
| --- | --- | ---: | ---: | --- |
| Complete exact-oracle conformance | `{integration_conformance['source_commit'][:8]}` | {integration_conformance['status_counts']['pass']} | {integration_conformance['status_counts']['fail']} | All {integration_conformance['inventory_total']} accounted for; {integration_conformance['timed_out']} timeouts |
| Complete whole upstream drivers | `{integration_upstream['source_commit'][:8]}` | {integration_upstream['by_kind']['whole']['pass']} | {integration_upstream['by_kind']['whole']['fail']} | {integration_upstream['by_kind']['whole']['skip']} skipped; all 70 accounted for |
| Complete curated upstream slices | `{integration_upstream['source_commit'][:8]}` | {integration_upstream['by_kind']['curated']['pass']} | {integration_upstream['by_kind']['curated']['fail']} | All 15 accounted for |
| Local complete Chromium showcase | `{integration_local['source_commit'][:8]}` | {integration_local['showcase']['stats']['expected']} | {integration_local['showcase']['stats']['unexpected']} | Original 59 plus reset regression; zero skipped or flaky |
| Linux complete Chromium showcase | `{integration_linux['source_commit'][:8]}` | {integration_linux['stats']['expected']} | {integration_linux['stats']['unexpected']} | All 60 accounted for; zero skipped or flaky |
| Complete native package integration | `{view['source_commit'][:8]}` | {view_checks['public_packages']['passed']} | {view_checks['public_packages']['failed']} | Both actual public constructor policies |
| Local complete Chromium showcase | `{view['source_commit'][:8]}` | {view_checks['chromium_complete']['expected']} | {view_checks['chromium_complete']['unexpected']} | Original 59 plus reset regression; zero skipped or flaky |
| Linux native package integration | `{view['source_commit'][:8]}` | {view['linux_public_packages']['passed']} | {view['linux_public_packages']['failed']} | Explicit empty and native policy; no host Rscript or R_HOME |
| Linux complete Chromium showcase | `{view['source_commit'][:8]}` | {view['linux_showcase']['stats']['expected']} | {view['linux_showcase']['stats']['unexpected']} | All 60 accounted for; zero skipped or flaky |
| Public native package/data workflows | `{integration_checks['native_packages_and_data']['source_commit'][:8]}` | {integration_checks['native_packages_and_data']['passed']} | {integration_checks['native_packages_and_data']['failed']} | Includes all 39 embedding tests and both actual constructor policies |
| Original Wasm dataset contracts | `{integration_checks['wasm_datasets']['source_commit'][:8]}` | {integration_checks['wasm_datasets']['passed']} | {integration_checks['wasm_datasets']['failed']} | 108 original objects; 91 topics; 592931 exact serialized graph bytes |
| Unchanged whole `eval-etc.R` | `c4de20b5` | 1 | 0 | Strict GNU comparison; graphics/native/faer release |
| Unchanged whole `structure.R` | `c4de20b5` | 1 | 0 | Strict GNU comparison; graphics/native/faer release |
| Unchanged whole `reg-S4.R` | `4b48f0b0` | 1 | 0 | Strict GNU comparison; graphics/native/faer release |

The latest independently verified complete inventory is recorded at
`91babc00` in the [complete inventory receipt](ci-checkpoints/complete-inventory-91babc00.json).
All six conformance producers and all five upstream producers agree on source,
corpus, pinned oracle and execution profile. The clean source tree independently
joins them without errors; semantic failures remain failures.

| Complete executed set | Pass | Fail | Other |
| --- | ---: | ---: | --- |
| Exact-oracle conformance | {complete['conformance']['status_counts']['pass']} | {complete['conformance']['status_counts']['fail']} | All 1181 accounted for; zero timeouts |
| Whole upstream drivers | {complete['upstream_by_kind']['whole']['pass']} | {complete['upstream_by_kind']['whole']['fail']} | 31 skipped; all 70 accounted for |
| Curated upstream slices | {complete['upstream_by_kind']['curated']['pass']} | 0 | All 15 accounted for |

This complete conformance report has seventeen fewer failures than the reviewed
checkpoint (five fewer than the preceding `4cd0f941` union). The upstream runtime
uses graphics/native/faer release with an 1800-second per-case deadline. UTF-8
completes with a strict output difference. GNU Latin-1 exits
successfully; the Rust native graphics operation still fails. Every outcome and
producer hash remains in the receipt. The randomized `p-r-random-tests.R` driver
now fails its Cauchy DKW check; its independently sampled seeds need a matched
reproduction before assigning a cause. The preceding `6ccae790` checkpoint
reported 17 whole-driver passes and 22 failures. Later selected checks are not added to
these totals. The preceding `4cd0f941` complete report had twelve fewer failures
than the reviewed checkpoint. Later selected case 538 passes after shared `try` rendering repairs;
case 540 still differs in warning call attribution. Selected checks do not alter
the complete union totals. The original `utils::data` closure now reaches its
portable package-shaped path and original serialized assets through the real
file/namespace routes. No helpers are injected into the global environment.
Public `require` emits real startup conditions and respects quiet and repeated
attachment; public `try` preserves nested and explicit condition calls. At
`f16592b7`, calling error handlers receive real conditions before unwind: the
original pinned GNU `.handleSimpleError` is installed in canonical base and called
with the handler, message and quoted originating call. Both constructor policies,
call-free and custom conditions, help-call attribution and callback collection
pass, together with 21 existing owned condition/restart controls and the same
public contract in two fresh production Wasm sessions.
The complete upstream union accounts for all 85 workloads under the explicit
graphics/native/faer release profile. UTF-8 completes
with a strict output difference. GNU Latin-1 setup succeeds; Rust explicitly
rejects the unfinished native `C_mtext` operation. Earlier incomplete or
shorter diagnostic reports retain their classifications.

Local methods profiling improves from 14.7/16.2 seconds to 10.528 seconds after
checked package-byte initialization. A later controlled comparison measures
9.920 seconds before amortized collection headroom and 6.058 seconds after it,
with cold initialization measured separately. The original 15-second evaluation,
64 MiB heap and 500000-node budgets remain unchanged. Immutable Linux `9b500c00`
passes all 60 showcase cases with zero skips or flaky results, including all
previous methods timeouts and both sunflower flows. Existing forced-GC and
64 MiB retention checks also pass. The earlier Linux failures remain in the receipt.

GNU instruction storage reduces the debug dispatcher frame from 27584 to 4416
bytes; existing private VM controls and strict Miri pass. Local production
`196e62eb` passes all 60 showcase cases. This source still reproduces the native
stack abort through the explicit portable constructor, despite passing native-host
checks. The later `52586600` checked-metadata storage repair passes all four grid
workflows under both policies at the unchanged stack budget, plus all 57 public
controls, 25 private VM controls, strict Miri, formatting and Clippy. Its immutable
Linux checkpoint also passes the original grid workflows under both policies and
all 60 browser tests. The Linux workspace advances to 38/39 embedding tests,
where the device-lifecycle workflow still depends on a missing host R
configuration file; this is tracked separately. The older exhaustive workspace run
is incomplete; it is not current-HEAD passing evidence.
The original GNU `grDevices` package image at `0105a3ff` provides canonical
namespace initialization and 137 captured exports under the explicit empty
portable library policy. The unchanged device-lifecycle workflow passes through
both real constructors after repairing the shared builtin `par` query path.
All 39 native embedding tests pass locally, along with seven namespace/window
controls and the original grid workflows. Two fresh production Wasm sessions
pass the same namespace/device workflow and encode a real PNG; all 205 original
dataset checks and the complete 60-case browser suite pass. A focused immutable
Linux package checkpoint completes all 46 public package checks without host R
discovery. The separate Linux browser workbench fails at serialized recording
because `Sys.getpid()` calls an unsupported host API on Wasm; its showcase
suite is not reached. The earlier local 60-case result remains separately
sourced. A broader forced-GC recording invocation was manually cancelled and
is not counted as complete. Captured exports do not imply that every export
has a completed native implementation.

The later `96742f34` repair gives native `try`/`tryCatch` an owned evaluation
context and correctly returns no inferred caller for a lone top-level builtin.
The original top-level stop cases and existing nested, explicit and callback
condition workflows pass through both public constructors. At `7a4f7314`,
`Sys.getpid()` uses a stable virtual process identity on browser Wasm, avoiding
the host API panic in the original GNU `recordPlot()` wrapper. Two fresh
production sessions pass the original six workbench plots, serialized replay,
all condition fixtures and all 205 dataset checks; the unchanged browser
workbench test and full 60-case showcase also pass locally.
The `c608eefa` CI repair keeps strict producer reports outside restored Cargo
caches. Its `4cd0f941` follow-up passes all 46 public package checks on Linux,
Wasm execution, Clippy, formatting and whole-script differential tests. Its
independently verified complete reports record 1057/1181 conformance passes,
16 whole-driver passes and all 15 curated slices passing. The complete Linux
showcase records 59 passes and one methods-workflow runtime timeout at the
unchanged 15-second budget. The older 60-pass Linux result remains separately
sourced. The earlier jobs that failed receipt admission do not supply driver
results. Its workspace job fails a Python runner stub before Cargo; that
tooling regression is repaired at `10ab9e72`, with all 131 script tests passing.

The `04c35a37` batch evaluation policy preserves user `.Last.value` bindings and
avoids automatic writes during scripts, while retaining console publication by
default. Both public constructor policies pass active-binding, collection,
error recovery and drawing controls. The four original `ls` cases and complete
`method-dispatch.R` driver pass strict comparison. Production Wasm passes the
original workbench test, 205 dataset checks and all 60 showcase cases locally.

The explicit native error-call repair at `1d06a03c` preserves the supplied
`letters@foo` call while retaining GNU inferred `stop` calls and callback
replacement attribution. The unchanged complete `method-dispatch.R` passes
strict comparison under graphics/native/faer release.

The table printing repair at `06773bdc` uses the original GNU closure and shared
output paths. Both public constructor policies match independently captured GNU
output for formatting options, dimensions, missing names and capture chronology.
The unchanged original conformance case 1091 and curated slice 008 also pass
strict comparison in the explicit release profile. These selected results do
not change the complete union counts above.

At `2b89a9eb`, all three original complex cases and the unchanged whole
`complex.R` driver pass strict GNU comparison. Public output preserves NA versus
NaN, signed zero, attributes and custom missing-value text. Original portable
stats and graphics images expose their captured namespaces and imports without
host discovery. The broader native run passes all 39 embedding cases but then
fails the original portable time-series namespace fixture; it is incomplete.
The `88e1f39b` follow-up repairs GNU group-generic registration in the base
namespace and shared lazy `get`/`get0` mode and inheritance admission. The
unchanged namespace fixture, ten focused public controls and eighteen owned
lookup controls pass. Production Wasm passes the same six GNU contracts in two
fresh sessions, and the whole `method-dispatch.R` driver passes strict comparison.
These selected results leave the complete union totals above unchanged. The
later completed Linux `04c35a37` browser report still has 59 passes and the same
one methods timeout; its older local 60-pass result remains separately sourced.

The `6ccae790` native-view repair retains the original allocation identity at
construction while preserving caller rooting and Unknown ownership. All 49
public package checks, 96 object checks and 97 memory checks pass. A focused
strict Miri slot-reuse regression confirms denied owning conversion and stale
generation rejection. The original methods browser case passes three consecutive
runs, and the complete local Chromium suite passes all 60 cases under unchanged
15-second evaluation and 25 MiB package budgets. Production Wasm also passes the
six GNU package contracts twice, all 205 dataset checks and the original six
plotting workflows twice. Quiet sequential Node measurements reduce the median
superclass workflow from 10.223 to 7.908 seconds. These results are recorded in
[native-view evidence](ci-checkpoints/native-view-methods-6ccae790.json). Its
immutable Linux checkpoint passes all 49 public package checks but records 56
showcase passes and four failures: the original methods timeout, both sunflower
flows, and the aggregate FFT/RNG test's 90-second limit. The native-view change
improves local measured execution but has not resolved Linux browser budgets. The unchanged original time-series
case 668 also passes strict GNU comparison at `88e1f39b`.

At `b9d1bef7`, the original public correlation wrapper matches independently
executed GNU behavior across all three methods and all five missing-row modes,
including admission, warnings, NA/NaN distinctions and matrix structure. All ten
native family checks and all 50 selected native package integration checks pass; two fresh production Wasm sessions pass the seven
shared GNU package contracts and all 205 dataset checks still pass. A strict
Miri regression validates both converted arguments under forced collection.
The complete enclosing `reg-tests-1a.R` and `reg-tests-1b.R` debug-profile drivers still exit
nonzero: the former lacks `C_palette`; the latter reaches its correlation checks
and later fails at font metrics and `C_PostScript`. These results are recorded
in [correlation evidence](ci-checkpoints/correlation-b9d1bef7.json) and do not
change the complete inventory totals above.

[Cold and warm workflow diagnostics](ci-checkpoints/wasm-workflow-profile-b9d1bef7.json)
retain raw-profile hashes and sampled CPU stacks from quiet sequential Node runs.
The named diagnostic module has byte-identical standard execution sections to
production. Original methods and sunflower sources and viewport remain unchanged;
these timings include profiling overhead and do not establish Linux Chromium
acceptance. The same diagnostic runs after the unchanged browser tests in the
next immutable Linux checkpoint.

The later immutable [Linux workflow checkpoint](ci-checkpoints/linux-workflow-profile-91babc00.json)
at `91babc00` passes all 50 selected public package integration checks and
58 of 60 Chromium cases, with zero skipped or flaky cases. Both original methods
cases and the aggregate FFT/RNG case pass. Both sunflower user flows still time
out. Quiet post-browser Node profiles run the exact original example cold and
warm, directly and after a prior plot; evaluation takes 19.0–19.9 seconds.
The sampled distribution kernels and duplication consume little time; environment
lookup and character/header/link bookkeeping are the useful next targets.
These diagnostics preserve the original 15-second evaluation budget.

The later immutable [Linux browser checkpoint](ci-checkpoints/linux-browser-c3824f42.json)
at `c3824f42` passes all 60 unchanged Chromium cases with zero skipped or flaky
results, including both original sunflower flows. The separate expanded native
batch times out after 41 completed passes; its remaining suites are unexecuted.
The native batch deadline is corrected separately, while browser budgets stay
unchanged. A later complete local `2920368c` package run passes all 52 checks;
both original sunflower flows also pass three fresh local browser repetitions.
These separate-source results are preserved distinctly in the receipt.

The focused [canonical character-read repair](ci-checkpoints/character-read-9f2f28a6.json)
at `9f2f28a6` passes the existing native projection controls, strict Miri and
nine Wasm public contracts in two fresh sessions. Three sequential production
Node runs of the unchanged sunflower example reduce median cold execution from
12.14 to 11.12 seconds and retain byte-identical PNG output. These local timings
are diagnostic; the later Linux `c3824f42` receipt records all 60 browser tests
passing, including both unchanged sunflower flows.

The [public binning workflow repair](ci-checkpoints/bincode-2920368c.json)
at `2920368c` connects the original `.bincode` closure through canonical base
initialization and typed internal dispatch to the existing kernel. Its endpoint,
coercion, error-order, compiled-call and histogram workflows pass against pinned
GNU output under both constructor policies and through the actual Wasm facade.
Forced collection and strict Miri preserve both original converted inputs and the
result. The complete unchanged `reg-tests-1a.R` driver is still red under explicit
graphics/native/faer release, now reaching the ARIMA setup order-admission error.

The [original ARIMA0 and print-gap repair](ci-checkpoints/arima0-print-f1dc3091.json)
at `f1dc3091` admits the original seven-entry model metadata and honors GNU's
active matrix/vector print gap, including scalar coercion and invalid arguments.
Seasonal ML/CSS workflows and exact output pass under both constructor policies;
12 production Wasm public contracts pass in two fresh sessions. Existing STARMA
20 native controls and the seasonal/regression collection control under strict
Miri pass. The complete unchanged `reg-tests-1a.R` still fails in the explicit
release profile, now after these sections at missing `utils::C_flushconsole`.

At `5483fec6`, [console and close public workflows](ci-checkpoints/utils-console-5483fec6.json)
connect the original utils native registration to the session flush callback and
restore GNU's base close generic and internal connection route. Original progress
bars, compiled flush calls, lazy close methods and connection closure match GNU
under both policies. All 54 selected native public tests pass in release; the
final optimized Wasm passes 13 contracts in two fresh sessions. The real callback
and collection test passes natively and in a refreshed strict-Miri test image.
The unchanged whole driver still fails later at explicitly unsupported `C_mtext`.

At `f148143c`, [palette and temporary-name public contracts](ci-checkpoints/palette-tempfile-f148143c.json)
pass under both constructors in two fresh sessions each, with original GNU output.
Nine production Wasm contracts pass twice; 205 dataset checks and six original
plot workflows per generation also pass. Namespace privacy/identity, palette
session state and native file/capture checks pass. The unchanged enclosing
`reg-tests-1a.R` completes with a Rust error in both debug and explicitly selected
release profiles: it now gets through palette, colour conversion, correlation
and Gaussian model examples, then lacks the original base `.bincode` wrapper.
This is not a whole-driver passing claim. The original PDF fixture tests palette
state while a device is selected; it does not verify PDF drawing output.

The receipt joins each selected inventory key to actual wrappers, implementation
paths, options, edge cases, profiles, source commits and raw-report hashes.

Run strict three-way parity with the pinned oracle, workspace tests, Miri and
platform checks for executable evidence. See `docs/safe-api-audit.md` for the
owned public API and bounded unsafe implementation, and
`docs/web-architecture.md` for the Rust browser runtime and its limits.
'''
output = root / 'docs/capability-evidence.md'
if args.check:
    if not output.exists() or output.read_text() != report:
        raise SystemExit('Capability inventory is stale; run python3 scripts/capability_report.py')
else:
    output.write_text(report)
