[package]
name = "r-embed"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "R interpreter embedding library"

[dependencies]
thiserror = { workspace = true }
rmath = { path = "../../rmath-rs/rmath", features = ["renderplot-device"] }
r-graphics-engine = { path = "../r-graphics-engine" }
r-device-android-headless = { path = "../r-device-android-headless" }
png = "0.17.13"  # for encoding captured native rasters from real R graphics devices to PNG

[dev-dependencies]
