[package]
name = "r-embed"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "R interpreter embedding library"

[dependencies]
thiserror = { workspace = true }
rmath = { path = "../../rmath-rs/rmath" }
r-graphics-engine = { path = "../r-graphics-engine" }
r-device-android-headless = { path = "../r-device-android-headless" }

[dev-dependencies]
png = "0.17.13"
