## Curated from r-source/tests/primitives.R:
## primitive classification smoke checks.
print(is.primitive(sum))
print(is.primitive(length))
print(is.primitive(c))
print(is.primitive(function(x) x))
print(typeof(sum))
print(typeof(length))
print(typeof(c))
print(is.primitive(base::sum))
print(is.primitive(base::length))
print(typeof(base::sum))
print(base::length(c(1, 2, 3)))
print(exists(".ArgsEnv", envir = baseenv(), inherits = FALSE))
print(exists(".GenericArgsEnv", envir = baseenv(), inherits = FALSE))
print(is.environment(base::.ArgsEnv))
print(is.environment(base::.GenericArgsEnv))
print(paste(names(formals(args(base::sum))), collapse = ","))
print(paste(names(formals(args(base::length))), collapse = ","))
print(paste(names(formals(args(base::c))), collapse = ","))
print(length(tools::langElts))
print(tools::langElts[1])
print(any(tools::langElts == "function"))
print("sum" %in% names(base::.GenericArgsEnv))
print("UseMethod" %in% names(base::.ArgsEnv))
print("(" %in% tools::langElts)
ff <- list(sum = sum, length = length)
print(paste(as.character(vapply(ff, is.primitive, logical(1L))), collapse = ","))
